import {
    CapabilityBundleDefinition,
    CapabilityCatalog,
    CapabilityDefinition,
    SectorPackDefinition,
} from '../../domain/security/SecurityTypes';

const CAPABILITY_REGISTRY_VERSION = 5;

const CAPABILITIES: CapabilityDefinition[] = [
    // Core platform
    {
        key: 'core.security.permissions.manage',
        productKey: 'core',
        moduleKey: 'security',
        permissions: ['security.permissions.manage', 'system.users', 'system.settings'],
        labelI18nKey: 'capability.core.security.permissions.manage.label',
        denyI18nKey: 'deny.core.security.permissions.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'view.manage',
        productKey: 'core',
        moduleKey: 'views',
        permissions: ['view.manage'],
        labelI18nKey: 'capability.view.manage.label',
        denyI18nKey: 'deny.view.manage',
        defaultScope: 'BRANCH',
    },
    {
        key: 'view.share',
        productKey: 'core',
        moduleKey: 'views',
        permissions: ['view.share', 'view.manage'],
        labelI18nKey: 'capability.view.share.label',
        denyI18nKey: 'deny.view.share',
        defaultScope: 'COMPANY',
    },
    {
        key: 'core.workflow.approve',
        productKey: 'core',
        moduleKey: 'workflow',
        permissions: ['workflow.approve', 'DOC.APPROVE', 'DOC.APPROVE_L1', 'DOC.APPROVE_L2'],
        labelI18nKey: 'capability.core.workflow.approve.label',
        denyI18nKey: 'deny.core.workflow.approve',
        defaultScope: 'BRANCH',
        policyGuards: [
            { guardKey: 'signature_approval_guard' },
            { guardKey: 'control_date_guard' },
        ],
    },
    {
        key: 'core.audit.view',
        productKey: 'core',
        moduleKey: 'audit',
        permissions: ['audit.view', 'system.logs'],
        labelI18nKey: 'capability.core.audit.view.label',
        denyI18nKey: 'deny.core.audit.view',
        defaultScope: 'COMPANY',
    },
    {
        key: 'core.reporting.view',
        productKey: 'core',
        moduleKey: 'reporting',
        permissions: ['reporting.view', 'reports.view_all', 'basic.reports'],
        labelI18nKey: 'capability.core.reporting.view.label',
        denyI18nKey: 'deny.core.reporting.view',
        defaultScope: 'COMPANY',
    },
    {
        key: 'core.reporting.export',
        productKey: 'core',
        moduleKey: 'reporting',
        permissions: ['reporting.export'],
        labelI18nKey: 'capability.core.reporting.export.label',
        denyI18nKey: 'deny.core.reporting.export',
        defaultScope: 'COMPANY',
        policyGuards: [{ guardKey: 'print_control_guard' }],
    },
    {
        key: 'core.attachments.manage',
        productKey: 'core',
        moduleKey: 'attachments',
        permissions: ['attachments.manage'],
        labelI18nKey: 'capability.core.attachments.manage.label',
        denyI18nKey: 'deny.core.attachments.manage',
        defaultScope: 'BRANCH',
    },
    {
        key: 'attachments.file.upload',
        productKey: 'core',
        moduleKey: 'attachments',
        permissions: ['attachments.file.upload', 'attachments.manage'],
        labelI18nKey: 'capability.attachments.file.upload.label',
        denyI18nKey: 'deny.attachments.file.upload',
        defaultScope: 'BRANCH',
    },
    {
        key: 'attachments.file.download',
        productKey: 'core',
        moduleKey: 'attachments',
        permissions: ['attachments.file.download', 'attachments.manage'],
        labelI18nKey: 'capability.attachments.file.download.label',
        denyI18nKey: 'deny.attachments.file.download',
        defaultScope: 'BRANCH',
    },
    {
        key: 'attachments.file.delete',
        productKey: 'core',
        moduleKey: 'attachments',
        permissions: ['attachments.file.delete', 'attachments.manage'],
        labelI18nKey: 'capability.attachments.file.delete.label',
        denyI18nKey: 'deny.attachments.file.delete',
        defaultScope: 'BRANCH',
    },
    {
        key: 'attachments.quota.manage',
        productKey: 'core',
        moduleKey: 'attachments',
        permissions: ['attachments.quota.manage', 'system.settings'],
        labelI18nKey: 'capability.attachments.quota.manage.label',
        denyI18nKey: 'deny.attachments.quota.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'attachments.storage.addon.assign',
        productKey: 'core',
        moduleKey: 'attachments',
        permissions: ['attachments.storage.addon.assign', 'system.settings'],
        labelI18nKey: 'capability.attachments.storage.addon.assign.label',
        denyI18nKey: 'deny.attachments.storage.addon.assign',
        defaultScope: 'COMPANY',
    },
    {
        key: 'license.concurrent_user.monitor',
        productKey: 'core',
        moduleKey: 'license',
        permissions: ['license.concurrent_user.monitor', 'system.settings'],
        labelI18nKey: 'capability.license.concurrent_user.monitor.label',
        denyI18nKey: 'deny.license.concurrent_user.monitor',
        defaultScope: 'COMPANY',
    },
    {
        key: 'license.concurrent_user.allocate',
        productKey: 'core',
        moduleKey: 'license',
        permissions: ['license.concurrent_user.allocate', 'system.settings'],
        labelI18nKey: 'capability.license.concurrent_user.allocate.label',
        denyI18nKey: 'deny.license.concurrent_user.allocate',
        defaultScope: 'COMPANY',
    },
    {
        key: 'core.integrations.sync',
        productKey: 'core',
        moduleKey: 'integrations',
        permissions: ['integrations.sync'],
        labelI18nKey: 'capability.core.integrations.sync.label',
        denyI18nKey: 'deny.core.integrations.sync',
        defaultScope: 'COMPANY',
    },
    {
        key: 'core.print.control',
        productKey: 'core',
        moduleKey: 'printing',
        permissions: ['print.control'],
        labelI18nKey: 'capability.core.print.control.label',
        denyI18nKey: 'deny.core.print.control',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'print_copy_limit_guard', config: { maxCopies: 1 } }],
    },

    // Product: Trade & Industry
    {
        key: 'ti.master.partner.manage',
        productKey: 'trade_industry',
        moduleKey: 'master_data',
        permissions: ['master.partner.manage', 'customers.manage', 'suppliers.manage'],
        labelI18nKey: 'capability.ti.master.partner.manage.label',
        denyI18nKey: 'deny.ti.master.partner.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'ti.master.item.manage',
        productKey: 'trade_industry',
        moduleKey: 'master_data',
        permissions: ['master.item.manage', 'inventory.view'],
        labelI18nKey: 'capability.ti.master.item.manage.label',
        denyI18nKey: 'deny.ti.master.item.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'ti.sales.invoice.create',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.create', 'sales.create'],
        labelI18nKey: 'capability.ti.sales.invoice.create.label',
        denyI18nKey: 'deny.ti.sales.invoice.create',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sales.invoice.create',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.create', 'sales.create', 'ti.sales.invoice.create'],
        labelI18nKey: 'capability.sales.invoice.create.label',
        denyI18nKey: 'deny.sales.invoice.create',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sales.invoice.read',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.read', 'sales.view', 'ti.sales.invoice.create'],
        labelI18nKey: 'capability.sales.invoice.read.label',
        denyI18nKey: 'deny.sales.invoice.read',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sales.invoice.update',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.update', 'sales.edit', 'sales.invoice.create', 'ti.sales.invoice.create'],
        labelI18nKey: 'capability.sales.invoice.update.label',
        denyI18nKey: 'deny.sales.invoice.update',
        defaultScope: 'BRANCH',
    },
    {
        key: 'ti.sales.invoice.post',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.post', 'sales.post', 'DOC.POST'],
        labelI18nKey: 'capability.ti.sales.invoice.post.label',
        denyI18nKey: 'deny.ti.sales.invoice.post',
        defaultScope: 'BRANCH',
        fieldRules: [
            { fieldKey: 'sales_invoice.exchange_rate', criteria: 'document.status != DRAFT', effect: 'READONLY' },
            { fieldKey: 'sales_invoice.print_count', criteria: 'document.status = POSTED', effect: 'READONLY' },
        ],
        policyGuards: [
            { guardKey: 'control_date_guard' },
            { guardKey: 'print_control_guard' },
            { guardKey: 'signature_approval_guard' },
        ],
    },
    {
        key: 'sales.invoice.post',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.post', 'sales.post', 'DOC.POST', 'ti.sales.invoice.post'],
        labelI18nKey: 'capability.sales.invoice.post.label',
        denyI18nKey: 'deny.sales.invoice.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'sales.invoice.print',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.print', 'print.control'],
        labelI18nKey: 'capability.sales.invoice.print.label',
        denyI18nKey: 'deny.sales.invoice.print',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'print_control_guard' }],
    },
    {
        key: 'sales.invoice.void',
        productKey: 'trade_industry',
        moduleKey: 'sales',
        permissions: ['sales.invoice.void', 'sales.void'],
        labelI18nKey: 'capability.sales.invoice.void.label',
        denyI18nKey: 'deny.sales.invoice.void',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'ti.purchase.invoice.create',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.create', 'purchases.create'],
        labelI18nKey: 'capability.ti.purchase.invoice.create.label',
        denyI18nKey: 'deny.ti.purchase.invoice.create',
        defaultScope: 'BRANCH',
    },
    {
        key: 'ti.purchase.invoice.post',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.post', 'purchases.post'],
        labelI18nKey: 'capability.ti.purchase.invoice.post.label',
        denyI18nKey: 'deny.ti.purchase.invoice.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'purchase.invoice.create',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.create', 'purchases.create', 'ti.purchase.invoice.create'],
        labelI18nKey: 'capability.purchase.invoice.create.label',
        denyI18nKey: 'deny.purchase.invoice.create',
        defaultScope: 'BRANCH',
    },
    {
        key: 'purchase.invoice.read',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.read', 'purchases.view', 'ti.purchase.invoice.create'],
        labelI18nKey: 'capability.purchase.invoice.read.label',
        denyI18nKey: 'deny.purchase.invoice.read',
        defaultScope: 'BRANCH',
    },
    {
        key: 'purchase.invoice.update',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.update', 'purchases.edit', 'purchase.invoice.create', 'ti.purchase.invoice.create'],
        labelI18nKey: 'capability.purchase.invoice.update.label',
        denyI18nKey: 'deny.purchase.invoice.update',
        defaultScope: 'BRANCH',
    },
    {
        key: 'purchase.invoice.post',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.post', 'purchases.post', 'DOC.POST', 'ti.purchase.invoice.post'],
        labelI18nKey: 'capability.purchase.invoice.post.label',
        denyI18nKey: 'deny.purchase.invoice.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'purchase.invoice.print',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.print', 'print.control'],
        labelI18nKey: 'capability.purchase.invoice.print.label',
        denyI18nKey: 'deny.purchase.invoice.print',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'print_control_guard' }],
    },
    {
        key: 'purchase.invoice.void',
        productKey: 'trade_industry',
        moduleKey: 'purchases',
        permissions: ['purchase.invoice.void', 'purchases.void', 'DOC.VOID'],
        labelI18nKey: 'capability.purchase.invoice.void.label',
        denyI18nKey: 'deny.purchase.invoice.void',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'inventory.stock_transfer.create',
        productKey: 'trade_industry',
        moduleKey: 'inventory',
        permissions: ['inventory.stock_transfer.create', 'inventory.transfer.create', 'inventory.edit'],
        labelI18nKey: 'capability.inventory.stock_transfer.create.label',
        denyI18nKey: 'deny.inventory.stock_transfer.create',
        defaultScope: 'BRANCH',
    },
    {
        key: 'inventory.stock_transfer.read',
        productKey: 'trade_industry',
        moduleKey: 'inventory',
        permissions: ['inventory.stock_transfer.read', 'inventory.transfer.read', 'inventory.view'],
        labelI18nKey: 'capability.inventory.stock_transfer.read.label',
        denyI18nKey: 'deny.inventory.stock_transfer.read',
        defaultScope: 'BRANCH',
    },
    {
        key: 'inventory.stock_transfer.update',
        productKey: 'trade_industry',
        moduleKey: 'inventory',
        permissions: ['inventory.stock_transfer.update', 'inventory.transfer.update', 'inventory.edit'],
        labelI18nKey: 'capability.inventory.stock_transfer.update.label',
        denyI18nKey: 'deny.inventory.stock_transfer.update',
        defaultScope: 'BRANCH',
    },
    {
        key: 'inventory.stock_transfer.post',
        productKey: 'trade_industry',
        moduleKey: 'inventory',
        permissions: ['inventory.stock_transfer.post', 'inventory.transfer.post', 'inventory.post', 'DOC.POST'],
        labelI18nKey: 'capability.inventory.stock_transfer.post.label',
        denyI18nKey: 'deny.inventory.stock_transfer.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'inventory.stock_transfer.print',
        productKey: 'trade_industry',
        moduleKey: 'inventory',
        permissions: ['inventory.stock_transfer.print', 'print.control'],
        labelI18nKey: 'capability.inventory.stock_transfer.print.label',
        denyI18nKey: 'deny.inventory.stock_transfer.print',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'print_control_guard' }],
    },
    {
        key: 'inventory.stock_transfer.void',
        productKey: 'trade_industry',
        moduleKey: 'inventory',
        permissions: ['inventory.stock_transfer.void', 'inventory.transfer.void', 'inventory.void', 'DOC.VOID'],
        labelI18nKey: 'capability.inventory.stock_transfer.void.label',
        denyI18nKey: 'deny.inventory.stock_transfer.void',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'accounting.journal_voucher.create',
        productKey: 'trade_industry',
        moduleKey: 'accounting',
        permissions: ['accounting.journal_voucher.create', 'accounting.journal.create', 'gl.create'],
        labelI18nKey: 'capability.accounting.journal_voucher.create.label',
        denyI18nKey: 'deny.accounting.journal_voucher.create',
        defaultScope: 'BRANCH',
    },
    {
        key: 'accounting.journal_voucher.read',
        productKey: 'trade_industry',
        moduleKey: 'accounting',
        permissions: ['accounting.journal_voucher.read', 'accounting.journal.read', 'gl.view'],
        labelI18nKey: 'capability.accounting.journal_voucher.read.label',
        denyI18nKey: 'deny.accounting.journal_voucher.read',
        defaultScope: 'BRANCH',
    },
    {
        key: 'accounting.journal_voucher.update',
        productKey: 'trade_industry',
        moduleKey: 'accounting',
        permissions: ['accounting.journal_voucher.update', 'accounting.journal.update', 'gl.edit'],
        labelI18nKey: 'capability.accounting.journal_voucher.update.label',
        denyI18nKey: 'deny.accounting.journal_voucher.update',
        defaultScope: 'BRANCH',
    },
    {
        key: 'accounting.journal_voucher.post',
        productKey: 'trade_industry',
        moduleKey: 'accounting',
        permissions: ['accounting.journal_voucher.post', 'accounting.journal.post', 'gl.post', 'JOURNAL_POST', 'ti.gl.journal.post', 'DOC.POST'],
        labelI18nKey: 'capability.accounting.journal_voucher.post.label',
        denyI18nKey: 'deny.accounting.journal_voucher.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'accounting.journal_voucher.print',
        productKey: 'trade_industry',
        moduleKey: 'accounting',
        permissions: ['accounting.journal_voucher.print', 'print.control'],
        labelI18nKey: 'capability.accounting.journal_voucher.print.label',
        denyI18nKey: 'deny.accounting.journal_voucher.print',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'print_control_guard' }],
    },
    {
        key: 'accounting.journal_voucher.void',
        productKey: 'trade_industry',
        moduleKey: 'accounting',
        permissions: ['accounting.journal_voucher.void', 'accounting.journal.void', 'gl.void', 'DOC.VOID'],
        labelI18nKey: 'capability.accounting.journal_voucher.void.label',
        denyI18nKey: 'deny.accounting.journal_voucher.void',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'ti.gl.journal.post',
        productKey: 'trade_industry',
        moduleKey: 'accounting',
        permissions: ['accounting.journal.post', 'gl.post', 'JOURNAL_POST'],
        labelI18nKey: 'capability.ti.gl.journal.post.label',
        denyI18nKey: 'deny.ti.gl.journal.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'accounting.foundation.coa.read',
        productKey: 'financial_platform',
        moduleKey: 'accounting_foundation',
        permissions: ['accounting.foundation.coa.read', 'gl.view', 'ti.gl.journal.post'],
        labelI18nKey: 'capability.accounting.foundation.coa.read.label',
        denyI18nKey: 'deny.accounting.foundation.coa.read',
        defaultScope: 'COMPANY',
    },
    {
        key: 'accounting.foundation.coa.manage',
        productKey: 'financial_platform',
        moduleKey: 'accounting_foundation',
        permissions: ['accounting.foundation.coa.manage', 'gl.edit', 'system.settings'],
        labelI18nKey: 'capability.accounting.foundation.coa.manage.label',
        denyI18nKey: 'deny.accounting.foundation.coa.manage',
        defaultScope: 'COMPANY',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'accounting.foundation.definitions.read',
        productKey: 'financial_platform',
        moduleKey: 'accounting_foundation',
        permissions: ['accounting.foundation.definitions.read', 'gl.view', 'system.settings'],
        labelI18nKey: 'capability.accounting.foundation.definitions.read.label',
        denyI18nKey: 'deny.accounting.foundation.definitions.read',
        defaultScope: 'COMPANY',
    },
    {
        key: 'accounting.foundation.definitions.manage',
        productKey: 'financial_platform',
        moduleKey: 'accounting_foundation',
        permissions: ['accounting.foundation.definitions.manage', 'gl.edit', 'system.settings'],
        labelI18nKey: 'capability.accounting.foundation.definitions.manage.label',
        denyI18nKey: 'deny.accounting.foundation.definitions.manage',
        defaultScope: 'COMPANY',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'accounting.foundation.resolution.execute',
        productKey: 'financial_platform',
        moduleKey: 'accounting_foundation',
        permissions: ['accounting.foundation.resolution.execute', 'gl.post', 'DOC.POST'],
        labelI18nKey: 'capability.accounting.foundation.resolution.execute.label',
        denyI18nKey: 'deny.accounting.foundation.resolution.execute',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'ti.reporting.operational.view',
        productKey: 'trade_industry',
        moduleKey: 'reporting',
        permissions: ['reporting.operational.view', 'sales.reports', 'inventory.reports'],
        labelI18nKey: 'capability.ti.reporting.operational.view.label',
        denyI18nKey: 'deny.ti.reporting.operational.view',
        defaultScope: 'COMPANY',
    },

    // Product: NGO
    {
        key: 'ngo.master.donor.manage',
        productKey: 'ngo',
        moduleKey: 'master_data',
        permissions: ['ngo.master.donor.manage'],
        labelI18nKey: 'capability.ngo.master.donor.manage.label',
        denyI18nKey: 'deny.ngo.master.donor.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'ngo.master.project.manage',
        productKey: 'ngo',
        moduleKey: 'master_data',
        permissions: ['ngo.master.project.manage'],
        labelI18nKey: 'capability.ngo.master.project.manage.label',
        denyI18nKey: 'deny.ngo.master.project.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'ngo.grant.create',
        productKey: 'ngo',
        moduleKey: 'grants',
        permissions: ['ngo.grant.create'],
        labelI18nKey: 'capability.ngo.grant.create.label',
        denyI18nKey: 'deny.ngo.grant.create',
        defaultScope: 'COMPANY',
    },
    {
        key: 'ngo.grant.approve',
        productKey: 'ngo',
        moduleKey: 'grants',
        permissions: ['ngo.grant.approve'],
        labelI18nKey: 'capability.ngo.grant.approve.label',
        denyI18nKey: 'deny.ngo.grant.approve',
        defaultScope: 'COMPANY',
        policyGuards: [{ guardKey: 'signature_approval_guard' }],
    },
    {
        key: 'ngo.disbursement.post',
        productKey: 'ngo',
        moduleKey: 'funds',
        permissions: ['ngo.disbursement.post'],
        labelI18nKey: 'capability.ngo.disbursement.post.label',
        denyI18nKey: 'deny.ngo.disbursement.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'ngo.budget.control.enforce',
        productKey: 'ngo',
        moduleKey: 'budgeting',
        permissions: ['ngo.budget.control.enforce'],
        labelI18nKey: 'capability.ngo.budget.control.enforce.label',
        denyI18nKey: 'deny.ngo.budget.control.enforce',
        defaultScope: 'COMPANY',
    },
    {
        key: 'ngo.reporting.donor.view',
        productKey: 'ngo',
        moduleKey: 'reporting',
        permissions: ['ngo.reporting.donor.view'],
        labelI18nKey: 'capability.ngo.reporting.donor.view.label',
        denyI18nKey: 'deny.ngo.reporting.donor.view',
        defaultScope: 'COMPANY',
    },
    {
        key: 'ngo.security.role.assign',
        productKey: 'ngo',
        moduleKey: 'security',
        permissions: ['ngo.security.role.assign', 'security.permissions.manage'],
        labelI18nKey: 'capability.ngo.security.role.assign.label',
        denyI18nKey: 'deny.ngo.security.role.assign',
        defaultScope: 'COMPANY',
    },

    // Product: Government
    {
        key: 'gov.master.entity.manage',
        productKey: 'government',
        moduleKey: 'master_data',
        permissions: ['gov.master.entity.manage'],
        labelI18nKey: 'capability.gov.master.entity.manage.label',
        denyI18nKey: 'deny.gov.master.entity.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'gov.procurement.request.create',
        productKey: 'government',
        moduleKey: 'procurement',
        permissions: ['gov.procurement.request.create', 'purchase.request.create'],
        labelI18nKey: 'capability.gov.procurement.request.create.label',
        denyI18nKey: 'deny.gov.procurement.request.create',
        defaultScope: 'BRANCH',
    },
    {
        key: 'gov.procurement.request.approve',
        productKey: 'government',
        moduleKey: 'procurement',
        permissions: ['gov.procurement.request.approve', 'purchases.approve'],
        labelI18nKey: 'capability.gov.procurement.request.approve.label',
        denyI18nKey: 'deny.gov.procurement.request.approve',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'signature_approval_guard' }],
    },
    {
        key: 'gov.commitment.post',
        productKey: 'government',
        moduleKey: 'budgetary_control',
        permissions: ['gov.commitment.post'],
        labelI18nKey: 'capability.gov.commitment.post.label',
        denyI18nKey: 'deny.gov.commitment.post',
        defaultScope: 'BRANCH',
        fieldRules: [
            { fieldKey: 'commitment.amount', criteria: 'amount > budget.available', effect: 'DENY' },
        ],
        policyGuards: [
            { guardKey: 'budget_ceiling_guard' },
            { guardKey: 'control_date_guard' },
            { guardKey: 'signature_approval_guard' },
        ],
    },
    {
        key: 'gov.tax.submit',
        productKey: 'government',
        moduleKey: 'tax',
        permissions: ['gov.tax.submit'],
        labelI18nKey: 'capability.gov.tax.submit.label',
        denyI18nKey: 'deny.gov.tax.submit',
        defaultScope: 'COMPANY',
    },
    {
        key: 'gov.budget.control.enforce',
        productKey: 'government',
        moduleKey: 'budgetary_control',
        permissions: ['gov.budget.control.enforce', 'gl.budgets'],
        labelI18nKey: 'capability.gov.budget.control.enforce.label',
        denyI18nKey: 'deny.gov.budget.control.enforce',
        defaultScope: 'COMPANY',
    },
    {
        key: 'gov.reporting.compliance.view',
        productKey: 'government',
        moduleKey: 'reporting',
        permissions: ['gov.reporting.compliance.view', 'reports.financial'],
        labelI18nKey: 'capability.gov.reporting.compliance.view.label',
        denyI18nKey: 'deny.gov.reporting.compliance.view',
        defaultScope: 'COMPANY',
    },
    {
        key: 'gov.security.role.assign',
        productKey: 'government',
        moduleKey: 'security',
        permissions: ['gov.security.role.assign', 'security.permissions.manage'],
        labelI18nKey: 'capability.gov.security.role.assign.label',
        denyI18nKey: 'deny.gov.security.role.assign',
        defaultScope: 'COMPANY',
    },

    // Product: Revenue Management
    {
        key: 'rev.master.service.manage',
        productKey: 'revenue',
        moduleKey: 'master_data',
        permissions: ['rev.master.service.manage'],
        labelI18nKey: 'capability.rev.master.service.manage.label',
        denyI18nKey: 'deny.rev.master.service.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'rev.case.open',
        productKey: 'revenue',
        moduleKey: 'operations',
        permissions: ['rev.case.open'],
        labelI18nKey: 'capability.rev.case.open.label',
        denyI18nKey: 'deny.rev.case.open',
        defaultScope: 'BRANCH',
    },
    {
        key: 'rev.billing.issue',
        productKey: 'revenue',
        moduleKey: 'billing',
        permissions: ['rev.billing.issue'],
        labelI18nKey: 'capability.rev.billing.issue.label',
        denyI18nKey: 'deny.rev.billing.issue',
        defaultScope: 'BRANCH',
    },
    {
        key: 'rev.collection.post',
        productKey: 'revenue',
        moduleKey: 'collections',
        permissions: ['rev.collection.post'],
        labelI18nKey: 'capability.rev.collection.post.label',
        denyI18nKey: 'deny.rev.collection.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'rev.adjustment.approve',
        productKey: 'revenue',
        moduleKey: 'collections',
        permissions: ['rev.adjustment.approve'],
        labelI18nKey: 'capability.rev.adjustment.approve.label',
        denyI18nKey: 'deny.rev.adjustment.approve',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'signature_approval_guard' }],
    },
    {
        key: 'rev.reconciliation.run',
        productKey: 'revenue',
        moduleKey: 'reconciliation',
        permissions: ['rev.reconciliation.run'],
        labelI18nKey: 'capability.rev.reconciliation.run.label',
        denyI18nKey: 'deny.rev.reconciliation.run',
        defaultScope: 'COMPANY',
    },
    {
        key: 'rev.reporting.collection.view',
        productKey: 'revenue',
        moduleKey: 'reporting',
        permissions: ['rev.reporting.collection.view'],
        labelI18nKey: 'capability.rev.reporting.collection.view.label',
        denyI18nKey: 'deny.rev.reporting.collection.view',
        defaultScope: 'COMPANY',
    },
    {
        key: 'rev.security.role.assign',
        productKey: 'revenue',
        moduleKey: 'security',
        permissions: ['rev.security.role.assign', 'security.permissions.manage'],
        labelI18nKey: 'capability.rev.security.role.assign.label',
        denyI18nKey: 'deny.rev.security.role.assign',
        defaultScope: 'COMPANY',
    },

    // Product: Payroll Tax
    {
        key: 'prtax.master.employee.manage',
        productKey: 'payroll_tax',
        moduleKey: 'master_data',
        permissions: ['prtax.master.employee.manage', 'hr.manage'],
        labelI18nKey: 'capability.prtax.master.employee.manage.label',
        denyI18nKey: 'deny.prtax.master.employee.manage',
        defaultScope: 'COMPANY',
    },
    {
        key: 'prtax.payroll.calculate',
        productKey: 'payroll_tax',
        moduleKey: 'payroll',
        permissions: ['prtax.payroll.calculate', 'hr.salaries'],
        labelI18nKey: 'capability.prtax.payroll.calculate.label',
        denyI18nKey: 'deny.prtax.payroll.calculate',
        defaultScope: 'BRANCH',
    },
    {
        key: 'prtax.payroll.post',
        productKey: 'payroll_tax',
        moduleKey: 'payroll',
        permissions: ['prtax.payroll.post', 'hr.salaries'],
        labelI18nKey: 'capability.prtax.payroll.post.label',
        denyI18nKey: 'deny.prtax.payroll.post',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'prtax.tax.return.submit',
        productKey: 'payroll_tax',
        moduleKey: 'tax',
        permissions: ['prtax.tax.return.submit'],
        labelI18nKey: 'capability.prtax.tax.return.submit.label',
        denyI18nKey: 'deny.prtax.tax.return.submit',
        defaultScope: 'COMPANY',
        policyGuards: [
            { guardKey: 'tax_period_open_guard' },
            { guardKey: 'signature_approval_guard' },
        ],
    },
    {
        key: 'prtax.tax.payment.post',
        productKey: 'payroll_tax',
        moduleKey: 'tax',
        permissions: ['prtax.tax.payment.post'],
        labelI18nKey: 'capability.prtax.tax.payment.post.label',
        denyI18nKey: 'deny.prtax.tax.payment.post',
        defaultScope: 'COMPANY',
        policyGuards: [{ guardKey: 'control_date_guard' }],
    },
    {
        key: 'prtax.reporting.tax.view',
        productKey: 'payroll_tax',
        moduleKey: 'reporting',
        permissions: ['prtax.reporting.tax.view', 'reports.financial'],
        labelI18nKey: 'capability.prtax.reporting.tax.view.label',
        denyI18nKey: 'deny.prtax.reporting.tax.view',
        defaultScope: 'COMPANY',
    },
    {
        key: 'prtax.admin.period.lock',
        productKey: 'payroll_tax',
        moduleKey: 'admin',
        permissions: ['prtax.admin.period.lock', 'gl.closing'],
        labelI18nKey: 'capability.prtax.admin.period.lock.label',
        denyI18nKey: 'deny.prtax.admin.period.lock',
        defaultScope: 'COMPANY',
    },
    {
        key: 'prtax.security.role.assign',
        productKey: 'payroll_tax',
        moduleKey: 'security',
        permissions: ['prtax.security.role.assign', 'security.permissions.manage'],
        labelI18nKey: 'capability.prtax.security.role.assign.label',
        denyI18nKey: 'deny.prtax.security.role.assign',
        defaultScope: 'COMPANY',
    },

    // Financial platform (enterprise scope)
    {
        key: 'accounting.period.close',
        productKey: 'financial_platform',
        moduleKey: 'accounting_close',
        permissions: ['accounting.period.close', 'gl.closing'],
        labelI18nKey: 'capability.accounting.period.close.label',
        denyI18nKey: 'deny.accounting.period.close',
        defaultScope: 'COMPANY',
        policyGuards: [{ guardKey: 'control_date_guard' }, { guardKey: 'signature_approval_guard' }],
    },
    {
        key: 'consolidation.run.start',
        productKey: 'financial_platform',
        moduleKey: 'consolidation',
        permissions: ['consolidation.run.start', 'gl.reports'],
        labelI18nKey: 'capability.consolidation.run.start.label',
        denyI18nKey: 'deny.consolidation.run.start',
        defaultScope: 'COMPANY',
    },
    {
        key: 'treasury.cash_position.update',
        productKey: 'financial_platform',
        moduleKey: 'treasury',
        permissions: ['treasury.cash_position.update', 'gl.banks', 'treasury.payment'],
        labelI18nKey: 'capability.treasury.cash_position.update.label',
        denyI18nKey: 'deny.treasury.cash_position.update',
        defaultScope: 'BRANCH',
    },
    {
        key: 'treasury.payment.run.execute',
        productKey: 'financial_platform',
        moduleKey: 'treasury',
        permissions: ['treasury.payment.run.execute', 'treasury.payment'],
        labelI18nKey: 'capability.treasury.payment.run.execute.label',
        denyI18nKey: 'deny.treasury.payment.run.execute',
        defaultScope: 'COMPANY',
        policyGuards: [{ guardKey: 'signature_approval_guard' }],
    },
    {
        key: 'grc.risk.assess',
        productKey: 'financial_platform',
        moduleKey: 'grc',
        permissions: ['grc.risk.assess', 'system.logs', 'system.settings'],
        labelI18nKey: 'capability.grc.risk.assess.label',
        denyI18nKey: 'deny.grc.risk.assess',
        defaultScope: 'COMPANY',
    },
    {
        key: 'revenue.contract.create',
        productKey: 'financial_platform',
        moduleKey: 'revenue',
        permissions: ['revenue.contract.create', 'sales.create'],
        labelI18nKey: 'capability.revenue.contract.create.label',
        denyI18nKey: 'deny.revenue.contract.create',
        defaultScope: 'COMPANY',
    },
    {
        key: 'revenue.recognition.run',
        productKey: 'financial_platform',
        moduleKey: 'revenue',
        permissions: ['revenue.recognition.run', 'gl.post'],
        labelI18nKey: 'capability.revenue.recognition.run.label',
        denyI18nKey: 'deny.revenue.recognition.run',
        defaultScope: 'COMPANY',
    },
    {
        key: 'sustainability.carbon.entry.post',
        productKey: 'financial_platform',
        moduleKey: 'sustainability',
        permissions: ['sustainability.carbon.entry.post', 'gl.post'],
        labelI18nKey: 'capability.sustainability.carbon.entry.post.label',
        denyI18nKey: 'deny.sustainability.carbon.entry.post',
        defaultScope: 'BRANCH',
    },
    {
        key: 'analytics.forecast.generate',
        productKey: 'financial_platform',
        moduleKey: 'analytics',
        permissions: ['analytics.forecast.generate', 'reports.financial', 'reports.view_all'],
        labelI18nKey: 'capability.analytics.forecast.generate.label',
        denyI18nKey: 'deny.analytics.forecast.generate',
        defaultScope: 'COMPANY',
    },
    {
        key: 'analytics.dashboard.financial.view',
        productKey: 'financial_platform',
        moduleKey: 'analytics',
        permissions: ['analytics.dashboard.financial.view', 'reports.financial', 'reports.view_all'],
        labelI18nKey: 'capability.analytics.dashboard.financial.view.label',
        denyI18nKey: 'deny.analytics.dashboard.financial.view',
        defaultScope: 'COMPANY',
    },

    // Sector extras
    {
        key: 'sector.manufacturing.production.plan',
        productKey: 'sector',
        moduleKey: 'manufacturing',
        permissions: ['sector.manufacturing.production.plan', 'production.manage'],
        labelI18nKey: 'capability.sector.manufacturing.production.plan.label',
        denyI18nKey: 'deny.sector.manufacturing.production.plan',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.manufacturing.mrp.run',
        productKey: 'sector',
        moduleKey: 'manufacturing',
        permissions: ['sector.manufacturing.mrp.run', 'production.manage'],
        labelI18nKey: 'capability.sector.manufacturing.mrp.run.label',
        denyI18nKey: 'deny.sector.manufacturing.mrp.run',
        defaultScope: 'COMPANY',
    },
    {
        key: 'sector.public_sector.tender.publish',
        productKey: 'sector',
        moduleKey: 'public_sector',
        permissions: ['sector.public_sector.tender.publish'],
        labelI18nKey: 'capability.sector.public_sector.tender.publish.label',
        denyI18nKey: 'deny.sector.public_sector.tender.publish',
        defaultScope: 'COMPANY',
    },
    {
        key: 'sector.public_sector.audit.export',
        productKey: 'sector',
        moduleKey: 'public_sector',
        permissions: ['sector.public_sector.audit.export', 'reporting.export'],
        labelI18nKey: 'capability.sector.public_sector.audit.export.label',
        denyI18nKey: 'deny.sector.public_sector.audit.export',
        defaultScope: 'COMPANY',
    },
    {
        key: 'sector.fuel.station.shift.close',
        productKey: 'sector',
        moduleKey: 'fuel',
        permissions: ['sector.fuel.station.shift.close'],
        labelI18nKey: 'capability.sector.fuel.station.shift.close.label',
        denyI18nKey: 'deny.sector.fuel.station.shift.close',
        defaultScope: 'BRANCH',
        policyGuards: [{ guardKey: 'signature_approval_guard' }],
    },
    {
        key: 'sector.fuel.station.tank.reconcile',
        productKey: 'sector',
        moduleKey: 'fuel',
        permissions: ['sector.fuel.station.tank.reconcile'],
        labelI18nKey: 'capability.sector.fuel.station.tank.reconcile.label',
        denyI18nKey: 'deny.sector.fuel.station.tank.reconcile',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.pharmacy.batch.expiry.control',
        productKey: 'sector',
        moduleKey: 'pharma',
        permissions: ['sector.pharmacy.batch.expiry.control', 'inventory.view'],
        labelI18nKey: 'capability.sector.pharmacy.batch.expiry.control.label',
        denyI18nKey: 'deny.sector.pharmacy.batch.expiry.control',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.transportation.trip.costing',
        productKey: 'sector',
        moduleKey: 'transportation',
        permissions: ['sector.transportation.trip.costing'],
        labelI18nKey: 'capability.sector.transportation.trip.costing.label',
        denyI18nKey: 'deny.sector.transportation.trip.costing',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.education.student.billing',
        productKey: 'sector',
        moduleKey: 'education',
        permissions: ['sector.education.student.billing'],
        labelI18nKey: 'capability.sector.education.student.billing.label',
        denyI18nKey: 'deny.sector.education.student.billing',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.healthwellness.appointment.billing',
        productKey: 'sector',
        moduleKey: 'health',
        permissions: ['sector.healthwellness.appointment.billing'],
        labelI18nKey: 'capability.sector.healthwellness.appointment.billing.label',
        denyI18nKey: 'deny.sector.healthwellness.appointment.billing',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.repair.workorder.manage',
        productKey: 'sector',
        moduleKey: 'service',
        permissions: ['sector.repair.workorder.manage'],
        labelI18nKey: 'capability.sector.repair.workorder.manage.label',
        denyI18nKey: 'deny.sector.repair.workorder.manage',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.tourism.package.costing',
        productKey: 'sector',
        moduleKey: 'tourism',
        permissions: ['sector.tourism.package.costing'],
        labelI18nKey: 'capability.sector.tourism.package.costing.label',
        denyI18nKey: 'deny.sector.tourism.package.costing',
        defaultScope: 'COMPANY',
    },
    {
        key: 'sector.construction.project.variation.approve',
        productKey: 'sector',
        moduleKey: 'construction',
        permissions: ['sector.construction.project.variation.approve'],
        labelI18nKey: 'capability.sector.construction.project.variation.approve.label',
        denyI18nKey: 'deny.sector.construction.project.variation.approve',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.media.campaign.costing',
        productKey: 'sector',
        moduleKey: 'media',
        permissions: ['sector.media.campaign.costing'],
        labelI18nKey: 'capability.sector.media.campaign.costing.label',
        denyI18nKey: 'deny.sector.media.campaign.costing',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.quarry.weightbridge.ticket.post',
        productKey: 'sector',
        moduleKey: 'quarry',
        permissions: ['sector.quarry.weightbridge.ticket.post'],
        labelI18nKey: 'capability.sector.quarry.weightbridge.ticket.post.label',
        denyI18nKey: 'deny.sector.quarry.weightbridge.ticket.post',
        defaultScope: 'BRANCH',
    },
    {
        key: 'sector.stone.dimension.pricing',
        productKey: 'sector',
        moduleKey: 'stone',
        permissions: ['sector.stone.dimension.pricing'],
        labelI18nKey: 'capability.sector.stone.dimension.pricing.label',
        denyI18nKey: 'deny.sector.stone.dimension.pricing',
        defaultScope: 'COMPANY',
    },
];

const BUNDLES: CapabilityBundleDefinition[] = [
    {
        key: 'bundle.core',
        productKey: 'core',
        labelI18nKey: 'bundle.core.label',
        capabilityKeys: CAPABILITIES.filter(c => c.productKey === 'core').map(c => c.key),
    },
    {
        key: 'bundle.trade_industry',
        productKey: 'trade_industry',
        labelI18nKey: 'bundle.trade_industry.label',
        capabilityKeys: CAPABILITIES.filter(c => c.productKey === 'trade_industry').map(c => c.key),
    },
    {
        key: 'bundle.ngo',
        productKey: 'ngo',
        labelI18nKey: 'bundle.ngo.label',
        capabilityKeys: CAPABILITIES.filter(c => c.productKey === 'ngo').map(c => c.key),
    },
    {
        key: 'bundle.government',
        productKey: 'government',
        labelI18nKey: 'bundle.government.label',
        capabilityKeys: CAPABILITIES.filter(c => c.productKey === 'government').map(c => c.key),
    },
    {
        key: 'bundle.revenue',
        productKey: 'revenue',
        labelI18nKey: 'bundle.revenue.label',
        capabilityKeys: CAPABILITIES.filter(c => c.productKey === 'revenue').map(c => c.key),
    },
    {
        key: 'bundle.payroll_tax',
        productKey: 'payroll_tax',
        labelI18nKey: 'bundle.payroll_tax.label',
        capabilityKeys: CAPABILITIES.filter(c => c.productKey === 'payroll_tax').map(c => c.key),
    },
    {
        key: 'bundle.financial_platform',
        productKey: 'financial_platform',
        labelI18nKey: 'bundle.financial_platform.label',
        capabilityKeys: CAPABILITIES.filter(c => c.productKey === 'financial_platform').map(c => c.key),
    },
];

const SECTOR_PACKS: SectorPackDefinition[] = [
    { key: 'sector_pack.advertising', labelI18nKey: 'sector_pack.advertising.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.media.campaign.costing'] },
    { key: 'sector_pack.educational_institutions', labelI18nKey: 'sector_pack.educational_institutions.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.education.student.billing'] },
    { key: 'sector_pack.health_wellness', labelI18nKey: 'sector_pack.health_wellness.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.healthwellness.appointment.billing'] },
    { key: 'sector_pack.ngo', labelI18nKey: 'sector_pack.ngo.label', bundleKeys: ['bundle.ngo'], capabilityKeys: [] },
    {
        key: 'sector_pack.public_sector',
        labelI18nKey: 'sector_pack.public_sector.label',
        bundleKeys: ['bundle.government'],
        capabilityKeys: ['sector.public_sector.tender.publish', 'sector.public_sector.audit.export'],
    },
    { key: 'sector_pack.repair_maintenance', labelI18nKey: 'sector_pack.repair_maintenance.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.repair.workorder.manage'] },
    { key: 'sector_pack.tourism', labelI18nKey: 'sector_pack.tourism.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.tourism.package.costing'] },
    { key: 'sector_pack.advisory_implementation', labelI18nKey: 'sector_pack.advisory_implementation.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.repair.workorder.manage'] },
    { key: 'sector_pack.financial_services', labelI18nKey: 'sector_pack.financial_services.label', bundleKeys: ['bundle.trade_industry', 'bundle.payroll_tax'], capabilityKeys: [] },
    { key: 'sector_pack.hitech_services', labelI18nKey: 'sector_pack.hitech_services.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: [] },
    { key: 'sector_pack.pharma_trade', labelI18nKey: 'sector_pack.pharma_trade.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.pharmacy.batch.expiry.control'] },
    { key: 'sector_pack.quarrying_mining', labelI18nKey: 'sector_pack.quarrying_mining.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.quarry.weightbridge.ticket.post'] },
    { key: 'sector_pack.schools', labelI18nKey: 'sector_pack.schools.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.education.student.billing'] },
    { key: 'sector_pack.transportation', labelI18nKey: 'sector_pack.transportation.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.transportation.trip.costing'] },
    { key: 'sector_pack.automotive', labelI18nKey: 'sector_pack.automotive.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.repair.workorder.manage'] },
    { key: 'sector_pack.food_beverage', labelI18nKey: 'sector_pack.food_beverage.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: [] },
    {
        key: 'sector_pack.manufacturing',
        labelI18nKey: 'sector_pack.manufacturing.label',
        bundleKeys: ['bundle.trade_industry'],
        capabilityKeys: ['sector.manufacturing.production.plan', 'sector.manufacturing.mrp.run'],
        reportTemplateKeys: ['report.manufacturing.wip', 'report.manufacturing.efficiency'],
    },
    {
        key: 'sector_pack.pharmaceutical_manufacturing',
        labelI18nKey: 'sector_pack.pharmaceutical_manufacturing.label',
        bundleKeys: ['bundle.trade_industry'],
        capabilityKeys: ['sector.manufacturing.production.plan', 'sector.manufacturing.mrp.run', 'sector.pharmacy.batch.expiry.control'],
    },
    { key: 'sector_pack.recycle_reuse', labelI18nKey: 'sector_pack.recycle_reuse.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.manufacturing.production.plan'] },
    { key: 'sector_pack.services', labelI18nKey: 'sector_pack.services.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: [] },
    { key: 'sector_pack.wholesale_retail', labelI18nKey: 'sector_pack.wholesale_retail.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: [] },
    { key: 'sector_pack.construction', labelI18nKey: 'sector_pack.construction.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.construction.project.variation.approve'] },
    {
        key: 'sector_pack.fuel_gas_stations',
        labelI18nKey: 'sector_pack.fuel_gas_stations.label',
        bundleKeys: ['bundle.trade_industry'],
        capabilityKeys: ['sector.fuel.station.shift.close', 'sector.fuel.station.tank.reconcile'],
        policyTemplateKeys: ['policy.fuel.shift_signature', 'policy.fuel.variance_limit'],
    },
    { key: 'sector_pack.media_entertainment', labelI18nKey: 'sector_pack.media_entertainment.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.media.campaign.costing'] },
    { key: 'sector_pack.pharmacy', labelI18nKey: 'sector_pack.pharmacy.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.pharmacy.batch.expiry.control'] },
    { key: 'sector_pack.religious_organizations', labelI18nKey: 'sector_pack.religious_organizations.label', bundleKeys: ['bundle.ngo'], capabilityKeys: [] },
    { key: 'sector_pack.stone_marble_glass', labelI18nKey: 'sector_pack.stone_marble_glass.label', bundleKeys: ['bundle.trade_industry'], capabilityKeys: ['sector.stone.dimension.pricing'] },
];

export class CapabilityRegistry {
    getVersion(): number {
        return CAPABILITY_REGISTRY_VERSION;
    }

    getCatalog(): CapabilityCatalog {
        return {
            capabilities: CAPABILITIES,
            bundles: BUNDLES,
            sectorPacks: SECTOR_PACKS,
        };
    }

    getCapabilityKeys(): string[] {
        return CAPABILITIES.map((item) => item.key);
    }

    getCapabilityLabelMap(): Record<string, string> {
        return CAPABILITIES.reduce((acc, item) => {
            acc[item.key] = item.labelI18nKey;
            return acc;
        }, {} as Record<string, string>);
    }

    getCapabilityRegistryRows(): Array<{
        capabilityKey: string;
        labelI18nKey: string;
        category: string;
        moduleKey: string;
        productKey: string;
        defaultScope: string;
    }> {
        return CAPABILITIES.map((item) => ({
            capabilityKey: item.key,
            labelI18nKey: item.labelI18nKey,
            category: `${item.productKey}.${item.moduleKey}`,
            moduleKey: item.moduleKey,
            productKey: item.productKey,
            defaultScope: item.defaultScope,
        }));
    }
}
