export enum FinancialDefinitionOwnerType {
    COMPANY = 'COMPANY',
    BRANCH = 'BRANCH',
    ITEM = 'ITEM',
    ITEM_GROUP = 'ITEM_GROUP',
    WAREHOUSE = 'WAREHOUSE',
    PARTNER = 'PARTNER',
    TAX_PROFILE = 'TAX_PROFILE',
    DOCUMENT_TYPE_DEFAULT = 'DOCUMENT_TYPE_DEFAULT',
}
