"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.chartOfAccountsSeed = void 0;
const AccountCategory_1 = require("../enums/AccountCategory");
const AccountSubtype_1 = require("../enums/AccountSubtype");
const NormalBalance_1 = require("../enums/NormalBalance");
const D = NormalBalance_1.NormalBalance.DEBIT;
const C = NormalBalance_1.NormalBalance.CREDIT;
const header = (code, name, category, parentCode, subtype = AccountSubtype_1.AccountSubtype.GROUP) => ({
    code,
    name,
    category,
    subtype,
    parentCode,
    isPosting: false,
    normalBalance: category === AccountCategory_1.AccountCategory.LIABILITY ||
        category === AccountCategory_1.AccountCategory.EQUITY ||
        category === AccountCategory_1.AccountCategory.REVENUE ||
        category === AccountCategory_1.AccountCategory.OTHER_INCOME
        ? C
        : D,
    systemTag: null,
    allowManualEntry: false,
    isActive: true,
});
const posting = (code, name, category, subtype, parentCode, normalBalance, options) => ({
    code,
    name,
    category,
    subtype,
    parentCode,
    isPosting: true,
    normalBalance,
    systemTag: options?.systemTag ?? null,
    allowManualEntry: options?.allowManualEntry ?? true,
    isActive: options?.isActive ?? true,
});
exports.chartOfAccountsSeed = [
    header('10000', 'Assets', AccountCategory_1.AccountCategory.ASSET, null, AccountSubtype_1.AccountSubtype.ROOT),
    header('11000', 'Current Assets', AccountCategory_1.AccountCategory.ASSET, '10000'),
    header('11100', 'Cash and Cash Equivalents', AccountCategory_1.AccountCategory.ASSET, '11000'),
    posting('11101', 'Main Cash', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CASH, '11100', D),
    posting('11102', 'POS Cash', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CASH, '11100', D),
    posting('11103', 'Petty Cash', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CASH, '11100', D),
    posting('11104', 'Bank ILS', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.BANK, '11100', D),
    posting('11105', 'Bank USD', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.BANK, '11100', D),
    posting('11106', 'Bank JOD', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.BANK, '11100', D),
    posting('11107', 'Undeposited Funds', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.UNDEPOSITED_FUNDS, '11100', D),
    header('11200', 'Trade Receivables', AccountCategory_1.AccountCategory.ASSET, '11000'),
    posting('11201', 'Accounts Receivable Control', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.RECEIVABLE_CONTROL, '11200', D, {
        systemTag: 'AR_CONTROL',
        allowManualEntry: false,
    }),
    posting('11202', 'Notes Receivable', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.RECEIVABLE_NOTE, '11200', D),
    posting('11203', 'Returned Cheques', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.RECEIVABLE_RETURNED_CHEQUE, '11200', D),
    posting('11204', 'Employee Receivables', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.RECEIVABLE_EMPLOYEE, '11200', D),
    posting('11205', 'Other Receivables', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.RECEIVABLE_OTHER, '11200', D),
    posting('11206', 'Allowance for Doubtful Debts', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.ALLOWANCE_DOUBTFUL_DEBTS, '11200', C, {
        allowManualEntry: false,
    }),
    header('11300', 'Inventory', AccountCategory_1.AccountCategory.ASSET, '11000'),
    posting('11301', 'Raw Materials Inventory', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.INVENTORY_RAW_MATERIAL, '11300', D),
    posting('11302', 'Work in Progress Inventory', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.INVENTORY_WIP, '11300', D),
    posting('11303', 'Finished Goods Inventory', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.INVENTORY_FINISHED_GOOD, '11300', D),
    posting('11304', 'Merchandise Inventory', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.INVENTORY_MERCHANDISE, '11300', D, {
        systemTag: 'INVENTORY_CONTROL',
        allowManualEntry: false,
    }),
    posting('11305', 'Goods in Transit', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.INVENTORY_GOODS_IN_TRANSIT, '11300', D),
    posting('11306', 'Inventory Adjustment Control', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.INVENTORY_ADJUSTMENT_CONTROL, '11300', D, {
        systemTag: 'INVENTORY_ADJUSTMENT_CONTROL',
        allowManualEntry: false,
    }),
    header('11400', 'Tax Recoverables', AccountCategory_1.AccountCategory.ASSET, '11000'),
    posting('11401', 'VAT Input Recoverable', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.TAX_INPUT_VAT, '11400', D, {
        systemTag: 'VAT_INPUT',
        allowManualEntry: false,
    }),
    posting('11402', 'Advance Tax Payments', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.TAX_ADVANCE, '11400', D),
    header('11500', 'Prepaid Expenses', AccountCategory_1.AccountCategory.ASSET, '11000'),
    posting('11501', 'Prepaid Rent', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.PREPAID_RENT, '11500', D),
    posting('11502', 'Prepaid Insurance', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.PREPAID_INSURANCE, '11500', D),
    posting('11503', 'Prepaid Contracts', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.PREPAID_CONTRACT, '11500', D),
    header('11600', 'Clearing Accounts', AccountCategory_1.AccountCategory.ASSET, '11000'),
    posting('11601', 'Branch Clearing', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CLEARING_BRANCH, '11600', D, {
        systemTag: 'BRANCH_CLEARING',
        allowManualEntry: false,
    }),
    posting('11602', 'Cash Transfer Clearing', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CLEARING_CASH_TRANSFER, '11600', D, {
        systemTag: 'CASH_TRANSFER_CLEARING',
        allowManualEntry: false,
    }),
    posting('11603', 'Bank Transfer Clearing', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CLEARING_BANK_TRANSFER, '11600', D, {
        systemTag: 'BANK_TRANSFER_CLEARING',
        allowManualEntry: false,
    }),
    header('11700', 'Cheques and Notes Receivable', AccountCategory_1.AccountCategory.ASSET, '11000'),
    posting('11701', 'Postdated Cheques Under Collection', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CHEQUE_RECEIVABLE, '11700', D, {
        systemTag: 'POSTDATED_CHEQUES_UNDER_COLLECTION',
        allowManualEntry: false,
    }),
    posting('11702', 'Cheques in Safe - ILS', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CHEQUE_RECEIVABLE, '11700', D, {
        systemTag: 'CHEQUES_IN_SAFE_ILS',
        allowManualEntry: false,
    }),
    posting('11703', 'Cheques in Safe - JOD', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CHEQUE_RECEIVABLE, '11700', D, {
        systemTag: 'CHEQUES_IN_SAFE_JOD',
        allowManualEntry: false,
    }),
    posting('11704', 'Cheques in Safe - USD', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CHEQUE_RECEIVABLE, '11700', D, {
        systemTag: 'CHEQUES_IN_SAFE_USD',
        allowManualEntry: false,
    }),
    posting('11705', 'Cheques Deposited to Bank', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CHEQUE_RECEIVABLE, '11700', D, {
        systemTag: 'CHEQUES_DEPOSITED_TO_BANK',
        allowManualEntry: false,
    }),
    posting('11706', 'Returned Customer Cheques', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.CHEQUE_RECEIVABLE, '11700', D, {
        systemTag: 'RETURNED_CUSTOMER_CHEQUES',
        allowManualEntry: false,
    }),
    header('12000', 'Non-Current Assets', AccountCategory_1.AccountCategory.ASSET, '10000'),
    header('12100', 'Property and Buildings', AccountCategory_1.AccountCategory.ASSET, '12000'),
    posting('12101', 'Land', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.FIXED_ASSET_LAND, '12100', D),
    posting('12102', 'Buildings at Cost', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.FIXED_ASSET_BUILDING, '12100', D),
    posting('12103', 'Accumulated Depreciation Buildings', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.ACCUMULATED_DEPRECIATION, '12100', C, {
        allowManualEntry: false,
    }),
    header('12200', 'Plant and Equipment', AccountCategory_1.AccountCategory.ASSET, '12000'),
    posting('12201', 'Machinery at Cost', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.FIXED_ASSET_MACHINERY, '12200', D),
    posting('12202', 'Accumulated Depreciation Machinery', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.ACCUMULATED_DEPRECIATION, '12200', C, {
        allowManualEntry: false,
    }),
    header('12300', 'Vehicles', AccountCategory_1.AccountCategory.ASSET, '12000'),
    posting('12301', 'Vehicles at Cost', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.FIXED_ASSET_VEHICLE, '12300', D, {
        systemTag: 'VEHICLES_COST',
        allowManualEntry: false,
    }),
    posting('12302', 'Accumulated Depreciation - Vehicles', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.ACCUMULATED_DEPRECIATION, '12300', C, {
        systemTag: 'ACC_DEPR_VEHICLES',
        allowManualEntry: false,
    }),
    header('12400', 'Furniture and Fixtures', AccountCategory_1.AccountCategory.ASSET, '12000'),
    posting('12401', 'Furniture at Cost', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.FIXED_ASSET_FURNITURE, '12400', D),
    posting('12402', 'Accumulated Depreciation Furniture', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.ACCUMULATED_DEPRECIATION, '12400', C, {
        allowManualEntry: false,
    }),
    header('12500', 'Computers and Software', AccountCategory_1.AccountCategory.ASSET, '12000'),
    posting('12501', 'Computers at Cost', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.FIXED_ASSET_COMPUTER, '12500', D),
    posting('12502', 'Software Licenses', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.FIXED_ASSET_SOFTWARE, '12500', D),
    posting('12503', 'Accumulated Depreciation Computers', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.ACCUMULATED_DEPRECIATION, '12500', C, {
        allowManualEntry: false,
    }),
    posting('12504', 'Accumulated Amortization Software', AccountCategory_1.AccountCategory.ASSET, AccountSubtype_1.AccountSubtype.ACCUMULATED_AMORTIZATION, '12500', C, {
        allowManualEntry: false,
    }),
    header('20000', 'Liabilities', AccountCategory_1.AccountCategory.LIABILITY, null, AccountSubtype_1.AccountSubtype.ROOT),
    header('21000', 'Current Liabilities', AccountCategory_1.AccountCategory.LIABILITY, '20000'),
    header('21100', 'Trade Payables', AccountCategory_1.AccountCategory.LIABILITY, '21000'),
    posting('21101', 'Accounts Payable Control', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.PAYABLE_CONTROL, '21100', C, {
        systemTag: 'AP_CONTROL',
        allowManualEntry: false,
    }),
    posting('21102', 'Notes Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.PAYABLE_NOTE, '21100', C),
    posting('21103', 'Other Trade Payables', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.PAYABLE_OTHER, '21100', C),
    header('21200', 'Accruals', AccountCategory_1.AccountCategory.LIABILITY, '21000'),
    posting('21201', 'Salaries Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.ACCRUED_EXPENSE, '21200', C),
    posting('21202', 'Rent Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.ACCRUED_EXPENSE, '21200', C),
    posting('21203', 'Utilities Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.ACCRUED_EXPENSE, '21200', C),
    posting('21204', 'Accrued Expenses', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.ACCRUED_EXPENSE, '21200', C),
    header('21300', 'Taxes Payable', AccountCategory_1.AccountCategory.LIABILITY, '21000'),
    posting('21301', 'VAT Output Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.TAX_OUTPUT_VAT, '21300', C, {
        systemTag: 'VAT_OUTPUT',
        allowManualEntry: false,
    }),
    posting('21302', 'Withholding Tax Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.TAX_WITHHOLDING, '21300', C),
    posting('21303', 'Income Tax Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.TAX_INCOME, '21300', C),
    header('21400', 'Customer Advances', AccountCategory_1.AccountCategory.LIABILITY, '21000'),
    posting('21401', 'Advances from Customers', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.CUSTOMER_ADVANCE, '21400', C),
    posting('21402', 'Unearned Revenue', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.UNEARNED_REVENUE, '21400', C),
    posting('21403', 'Gift Card Liability', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.GIFT_CARD_LIABILITY, '21400', C),
    header('21500', 'Other Current Liabilities', AccountCategory_1.AccountCategory.LIABILITY, '21000'),
    posting('21501', 'Short-Term Loans', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.LOAN_SHORT_TERM, '21500', C),
    posting('21502', 'Credit Card Settlement Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.CREDIT_CARD_SETTLEMENT, '21500', C),
    header('21600', 'Issued and Postdated Cheques', AccountCategory_1.AccountCategory.LIABILITY, '21000'),
    posting('21601', 'Postdated Cheques Payable', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.CHEQUE_PAYABLE, '21600', C, {
        systemTag: 'POSTDATED_CHEQUES_PAYABLE',
        allowManualEntry: false,
    }),
    posting('21602', 'Issued Cheques Under Clearing', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.CHEQUE_PAYABLE, '21600', C, {
        systemTag: 'ISSUED_CHEQUES_UNDER_CLEARING',
        allowManualEntry: false,
    }),
    header('22000', 'Non-Current Liabilities', AccountCategory_1.AccountCategory.LIABILITY, '20000'),
    header('22100', 'Long-Term Loans', AccountCategory_1.AccountCategory.LIABILITY, '22000'),
    posting('22101', 'Bank Loan Long Term', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.LOAN_LONG_TERM, '22100', C),
    posting('22102', 'Lease Liability Long Term', AccountCategory_1.AccountCategory.LIABILITY, AccountSubtype_1.AccountSubtype.LEASE_LONG_TERM, '22100', C),
    header('30000', 'Equity', AccountCategory_1.AccountCategory.EQUITY, null, AccountSubtype_1.AccountSubtype.ROOT),
    header('31000', 'Paid-in Capital', AccountCategory_1.AccountCategory.EQUITY, '30000'),
    posting('31101', 'Owner Capital', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.OWNER_CAPITAL, '31000', C),
    posting('31102', 'Partner Capital', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.PARTNER_CAPITAL, '31000', C),
    posting('31103', 'Additional Paid-in Capital', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.ADDITIONAL_PAID_IN_CAPITAL, '31000', C),
    header('32000', 'Reserves', AccountCategory_1.AccountCategory.EQUITY, '30000'),
    posting('32101', 'Statutory Reserve', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.STATUTORY_RESERVE, '32000', C),
    posting('32102', 'General Reserve', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.GENERAL_RESERVE, '32000', C),
    header('33000', 'Retained Earnings', AccountCategory_1.AccountCategory.EQUITY, '30000'),
    posting('33101', 'Retained Earnings Prior Years', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.RETAINED_EARNINGS, '33000', C),
    posting('33102', 'Current Year Earnings', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.RETAINED_EARNINGS, '33000', C),
    header('34000', 'Drawings', AccountCategory_1.AccountCategory.EQUITY, '30000'),
    posting('34101', 'Owner Drawings', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.OWNER_DRAWINGS, '34000', D),
    posting('34102', 'Partner Drawings', AccountCategory_1.AccountCategory.EQUITY, AccountSubtype_1.AccountSubtype.PARTNER_DRAWINGS, '34000', D),
    header('40000', 'Revenue', AccountCategory_1.AccountCategory.REVENUE, null, AccountSubtype_1.AccountSubtype.ROOT),
    header('41000', 'Sales Revenue', AccountCategory_1.AccountCategory.REVENUE, '40000'),
    posting('41101', 'Retail Sales', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.SALES_REVENUE, '41000', C),
    posting('41102', 'Wholesale Sales', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.SALES_REVENUE, '41000', C),
    posting('41103', 'E-Commerce Sales', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.SALES_REVENUE, '41000', C),
    posting('41104', 'Export Sales', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.SALES_REVENUE, '41000', C),
    posting('41105', 'Service Revenue', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.SERVICE_REVENUE, '41000', C),
    posting('41106', 'Delivery Revenue', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.DELIVERY_REVENUE, '41000', C),
    header('42000', 'Sales Deductions', AccountCategory_1.AccountCategory.REVENUE, '40000'),
    posting('42101', 'Sales Returns', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.SALES_RETURN, '42000', D),
    posting('42102', 'Sales Discounts Allowed', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.SALES_DISCOUNT, '42000', D),
    posting('42103', 'Promotional Discounts', AccountCategory_1.AccountCategory.REVENUE, AccountSubtype_1.AccountSubtype.PROMOTIONAL_DISCOUNT, '42000', D),
    header('50000', 'Cost of Sales', AccountCategory_1.AccountCategory.COST_OF_SALES, null, AccountSubtype_1.AccountSubtype.ROOT),
    header('51000', 'Cost of Goods Sold', AccountCategory_1.AccountCategory.COST_OF_SALES, '50000'),
    posting('51101', 'COGS Retail', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.COGS, '51000', D),
    posting('51102', 'COGS Wholesale', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.COGS, '51000', D),
    posting('51103', 'COGS E-Commerce', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.COGS, '51000', D),
    posting('51104', 'COGS Export', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.COGS, '51000', D),
    header('52000', 'Purchase Adjustments', AccountCategory_1.AccountCategory.COST_OF_SALES, '50000'),
    posting('52101', 'Purchase Returns', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.PURCHASE_RETURN, '52000', C),
    posting('52102', 'Purchase Discounts Earned', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.PURCHASE_DISCOUNT, '52000', C),
    posting('52103', 'Freight In', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.FREIGHT_IN, '52000', D),
    posting('52104', 'Customs and Import Charges', AccountCategory_1.AccountCategory.COST_OF_SALES, AccountSubtype_1.AccountSubtype.CUSTOMS_IMPORT, '52000', D),
    header('60000', 'Operating Expenses', AccountCategory_1.AccountCategory.EXPENSE, null, AccountSubtype_1.AccountSubtype.ROOT),
    header('61000', 'Payroll Expenses', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('61101', 'Basic Salaries', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.PAYROLL_EXPENSE, '61000', D),
    posting('61102', 'Wages', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.PAYROLL_EXPENSE, '61000', D),
    posting('61103', 'Bonuses', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.PAYROLL_EXPENSE, '61000', D),
    posting('61104', 'Employer Social Security', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.PAYROLL_EXPENSE, '61000', D),
    header('62000', 'Occupancy Expenses', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('62101', 'Rent Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.OCCUPANCY_EXPENSE, '62000', D),
    posting('62102', 'Electricity Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.OCCUPANCY_EXPENSE, '62000', D),
    posting('62103', 'Water Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.OCCUPANCY_EXPENSE, '62000', D),
    posting('62104', 'Municipality Fees', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.OCCUPANCY_EXPENSE, '62000', D),
    header('63000', 'Selling and Marketing', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('63101', 'Advertising Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.SELLING_MARKETING_EXPENSE, '63000', D),
    posting('63102', 'Social Media Ads', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.SELLING_MARKETING_EXPENSE, '63000', D),
    posting('63103', 'Sales Commissions', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.SELLING_MARKETING_EXPENSE, '63000', D),
    posting('63104', 'Packaging Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.SELLING_MARKETING_EXPENSE, '63000', D),
    posting('63105', 'Delivery Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.SELLING_MARKETING_EXPENSE, '63000', D),
    header('64000', 'Administrative Expenses', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('64101', 'Office Supplies', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.ADMINISTRATIVE_EXPENSE, '64000', D),
    posting('64102', 'Printing and Stationery', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.ADMINISTRATIVE_EXPENSE, '64000', D),
    posting('64103', 'Legal and Professional Fees', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.ADMINISTRATIVE_EXPENSE, '64000', D),
    posting('64104', 'Bank Charges', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.ADMINISTRATIVE_EXPENSE, '64000', D),
    posting('64105', 'Licenses and Permits', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.ADMINISTRATIVE_EXPENSE, '64000', D),
    posting('64106', 'Travel Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.ADMINISTRATIVE_EXPENSE, '64000', D),
    posting('64107', 'SaaS Subscriptions', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.ADMINISTRATIVE_EXPENSE, '64000', D),
    header('65000', 'IT and Communications', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('65101', 'Telephone Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.IT_COMMUNICATION_EXPENSE, '65000', D),
    posting('65102', 'Internet Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.IT_COMMUNICATION_EXPENSE, '65000', D),
    posting('65103', 'Hosting Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.IT_COMMUNICATION_EXPENSE, '65000', D),
    posting('65104', 'Software Subscriptions', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.IT_COMMUNICATION_EXPENSE, '65000', D),
    header('66000', 'Maintenance and Repairs', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('66101', 'Equipment Maintenance', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.MAINTENANCE_REPAIR_EXPENSE, '66000', D),
    posting('66102', 'Vehicle Maintenance', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.MAINTENANCE_REPAIR_EXPENSE, '66000', D),
    posting('66103', 'Building Maintenance', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.MAINTENANCE_REPAIR_EXPENSE, '66000', D),
    header('66200', 'Vehicle Operating Expenses', AccountCategory_1.AccountCategory.EXPENSE, '66000'),
    posting('66201', 'Fuel Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'FUEL_EXPENSE',
    }),
    posting('66202', 'Vehicle Maintenance and Repairs', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'VEHICLE_MAINTENANCE',
    }),
    posting('66203', 'Vehicle Insurance', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'VEHICLE_INSURANCE',
    }),
    posting('66204', 'Vehicle Licensing and Registration', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'VEHICLE_LICENSING',
    }),
    posting('66205', 'Tires and Consumables', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'VEHICLE_TIRES',
    }),
    posting('66206', 'Vehicle Lease or Rental Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'VEHICLE_LEASE',
    }),
    posting('66207', 'Vehicle Cleaning and Washing', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'VEHICLE_CLEANING',
    }),
    posting('66208', 'Vehicle Tracking and Fleet Systems', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'VEHICLE_TRACKING',
    }),
    posting('66209', 'Other Vehicle Expenses', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.VEHICLE_EXPENSE, '66200', D, {
        systemTag: 'OTHER_VEHICLE_EXPENSES',
    }),
    header('67000', 'Depreciation and Amortization', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('67101', 'Depreciation Buildings', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.DEPRECIATION_AMORTIZATION_EXPENSE, '67000', D),
    posting('67102', 'Depreciation Machinery', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.DEPRECIATION_AMORTIZATION_EXPENSE, '67000', D),
    posting('67103', 'Depreciation Vehicles', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.DEPRECIATION_AMORTIZATION_EXPENSE, '67000', D),
    posting('67104', 'Depreciation Furniture', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.DEPRECIATION_AMORTIZATION_EXPENSE, '67000', D),
    posting('67105', 'Depreciation Computers', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.DEPRECIATION_AMORTIZATION_EXPENSE, '67000', D),
    posting('67106', 'Amortization Software', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.DEPRECIATION_AMORTIZATION_EXPENSE, '67000', D),
    header('68000', 'Credit Losses', AccountCategory_1.AccountCategory.EXPENSE, '60000'),
    posting('68101', 'Bad Debt Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.CREDIT_LOSS_EXPENSE, '68000', D),
    posting('68102', 'Doubtful Debt Provision Expense', AccountCategory_1.AccountCategory.EXPENSE, AccountSubtype_1.AccountSubtype.CREDIT_LOSS_EXPENSE, '68000', D),
    header('70000', 'Other Income', AccountCategory_1.AccountCategory.OTHER_INCOME, null, AccountSubtype_1.AccountSubtype.ROOT),
    posting('71101', 'Gain on Asset Disposal', AccountCategory_1.AccountCategory.OTHER_INCOME, AccountSubtype_1.AccountSubtype.GAIN_ASSET_DISPOSAL, '70000', C),
    posting('71102', 'Foreign Exchange Gain', AccountCategory_1.AccountCategory.OTHER_INCOME, AccountSubtype_1.AccountSubtype.FX_GAIN, '70000', C),
    posting('71103', 'Miscellaneous Income', AccountCategory_1.AccountCategory.OTHER_INCOME, AccountSubtype_1.AccountSubtype.MISC_INCOME, '70000', C),
    header('80000', 'Other Expenses', AccountCategory_1.AccountCategory.OTHER_EXPENSE, null, AccountSubtype_1.AccountSubtype.ROOT),
    posting('81101', 'Loss on Asset Disposal', AccountCategory_1.AccountCategory.OTHER_EXPENSE, AccountSubtype_1.AccountSubtype.LOSS_ASSET_DISPOSAL, '80000', D),
    posting('81102', 'Foreign Exchange Loss', AccountCategory_1.AccountCategory.OTHER_EXPENSE, AccountSubtype_1.AccountSubtype.FX_LOSS, '80000', D),
    posting('81103', 'Penalties and Fines', AccountCategory_1.AccountCategory.OTHER_EXPENSE, AccountSubtype_1.AccountSubtype.PENALTIES_FINES, '80000', D),
    posting('81104', 'Miscellaneous Losses', AccountCategory_1.AccountCategory.OTHER_EXPENSE, AccountSubtype_1.AccountSubtype.MISC_EXPENSE, '80000', D),
    header('90000', 'Control and Closing', AccountCategory_1.AccountCategory.CONTROL, null, AccountSubtype_1.AccountSubtype.ROOT),
    posting('91101', 'Suspense Account', AccountCategory_1.AccountCategory.CONTROL, AccountSubtype_1.AccountSubtype.SUSPENSE, '90000', D, {
        systemTag: 'SUSPENSE_ACCOUNT',
        allowManualEntry: false,
    }),
    posting('91102', 'Opening Balance Equity', AccountCategory_1.AccountCategory.CONTROL, AccountSubtype_1.AccountSubtype.OPENING_BALANCE_EQUITY, '90000', C, {
        systemTag: 'OPENING_BALANCE_EQUITY',
        allowManualEntry: false,
    }),
    posting('91103', 'Rounding Difference Account', AccountCategory_1.AccountCategory.CONTROL, AccountSubtype_1.AccountSubtype.ROUNDING_DIFFERENCE, '90000', D, {
        systemTag: 'ROUNDING_DIFFERENCE',
        allowManualEntry: false,
    }),
    posting('92101', 'Profit and Loss Closing', AccountCategory_1.AccountCategory.CONTROL, AccountSubtype_1.AccountSubtype.CLOSING_PROFIT_LOSS, '90000', C, {
        systemTag: 'PROFIT_LOSS_CLOSING',
        allowManualEntry: false,
    }),
    posting('92102', 'Inventory Closing Adjustment', AccountCategory_1.AccountCategory.CONTROL, AccountSubtype_1.AccountSubtype.CLOSING_INVENTORY_ADJUSTMENT, '90000', D, {
        systemTag: 'INVENTORY_CLOSING_ADJUSTMENT',
        allowManualEntry: false,
    }),
];
