export enum AccountMappingKey {
    RECEIVABLE = 'RECEIVABLE',
    PAYABLE = 'PAYABLE',
    REVENUE = 'REVENUE',
    EXPENSE = 'EXPENSE',
    INVENTORY = 'INVENTORY',
    COGS = 'COGS',
    TAX_PAYABLE = 'TAX_PAYABLE',
    TAX_RECEIVABLE = 'TAX_RECEIVABLE',
    DISCOUNT = 'DISCOUNT',
    ROUNDING = 'ROUNDING',
}

