export enum AccountCategory {
    CURRENT_ASSET = 'CURRENT_ASSET',
    NON_CURRENT_ASSET = 'NON_CURRENT_ASSET',
    CURRENT_LIABILITY = 'CURRENT_LIABILITY',
    NON_CURRENT_LIABILITY = 'NON_CURRENT_LIABILITY',
    EQUITY = 'EQUITY',
    OPERATING_REVENUE = 'OPERATING_REVENUE',
    OTHER_REVENUE = 'OTHER_REVENUE',
    OPERATING_EXPENSE = 'OPERATING_EXPENSE',
    OTHER_EXPENSE = 'OTHER_EXPENSE',
    CONTROL = 'CONTROL',
    TAX = 'TAX',
    GENERAL = 'GENERAL',
}

