"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FinancialAccountRole = void 0;
var FinancialAccountRole;
(function (FinancialAccountRole) {
    FinancialAccountRole["RECEIVABLE_ACCOUNT"] = "RECEIVABLE_ACCOUNT";
    FinancialAccountRole["PAYABLE_ACCOUNT"] = "PAYABLE_ACCOUNT";
    FinancialAccountRole["REVENUE_ACCOUNT"] = "REVENUE_ACCOUNT";
    FinancialAccountRole["SERVICE_REVENUE_ACCOUNT"] = "SERVICE_REVENUE_ACCOUNT";
    FinancialAccountRole["EXPENSE_ACCOUNT"] = "EXPENSE_ACCOUNT";
    FinancialAccountRole["INVENTORY_ACCOUNT"] = "INVENTORY_ACCOUNT";
    FinancialAccountRole["RAW_MATERIAL_INVENTORY_ACCOUNT"] = "RAW_MATERIAL_INVENTORY_ACCOUNT";
    FinancialAccountRole["WIP_INVENTORY_ACCOUNT"] = "WIP_INVENTORY_ACCOUNT";
    FinancialAccountRole["FINISHED_GOODS_INVENTORY_ACCOUNT"] = "FINISHED_GOODS_INVENTORY_ACCOUNT";
    FinancialAccountRole["MERCHANDISE_INVENTORY_ACCOUNT"] = "MERCHANDISE_INVENTORY_ACCOUNT";
    FinancialAccountRole["COGS_ACCOUNT"] = "COGS_ACCOUNT";
    FinancialAccountRole["PURCHASE_RETURN_ACCOUNT"] = "PURCHASE_RETURN_ACCOUNT";
    FinancialAccountRole["SALES_RETURN_ACCOUNT"] = "SALES_RETURN_ACCOUNT";
    FinancialAccountRole["SALES_DISCOUNT_ACCOUNT"] = "SALES_DISCOUNT_ACCOUNT";
    FinancialAccountRole["PURCHASE_DISCOUNT_ACCOUNT"] = "PURCHASE_DISCOUNT_ACCOUNT";
    FinancialAccountRole["VAT_INPUT_ACCOUNT"] = "VAT_INPUT_ACCOUNT";
    FinancialAccountRole["VAT_OUTPUT_ACCOUNT"] = "VAT_OUTPUT_ACCOUNT";
    FinancialAccountRole["WITHHOLDING_TAX_ACCOUNT"] = "WITHHOLDING_TAX_ACCOUNT";
    FinancialAccountRole["ROUNDING_ACCOUNT"] = "ROUNDING_ACCOUNT";
    FinancialAccountRole["FREIGHT_IN_ACCOUNT"] = "FREIGHT_IN_ACCOUNT";
    FinancialAccountRole["INVENTORY_ADJUSTMENT_ACCOUNT"] = "INVENTORY_ADJUSTMENT_ACCOUNT";
    FinancialAccountRole["PRICE_DIFFERENCE_ACCOUNT"] = "PRICE_DIFFERENCE_ACCOUNT";
    FinancialAccountRole["SUSPENSE_ACCOUNT"] = "SUSPENSE_ACCOUNT";
    FinancialAccountRole["CASH_ACCOUNT"] = "CASH_ACCOUNT";
    FinancialAccountRole["BANK_ACCOUNT"] = "BANK_ACCOUNT";
    FinancialAccountRole["CHEQUE_IN_SAFE_ACCOUNT"] = "CHEQUE_IN_SAFE_ACCOUNT";
    FinancialAccountRole["CHEQUES_DEPOSITED_ACCOUNT"] = "CHEQUES_DEPOSITED_ACCOUNT";
    FinancialAccountRole["RETURNED_CHEQUE_ACCOUNT"] = "RETURNED_CHEQUE_ACCOUNT";
    FinancialAccountRole["ISSUED_CHEQUE_ACCOUNT"] = "ISSUED_CHEQUE_ACCOUNT";
    FinancialAccountRole["BANK_CLEARING_ACCOUNT"] = "BANK_CLEARING_ACCOUNT";
})(FinancialAccountRole || (exports.FinancialAccountRole = FinancialAccountRole = {}));
