"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerCustomerReceivablesIPC = registerCustomerReceivablesIPC;
const electron_1 = require("electron");
const ipcWrap_1 = require("../core/ipcWrap");
const withGuards_1 = require("./withGuards");
const LEGACY_PERMISSIONS = {
    READ: ['customer.view', 'receivables.view', 'collections.view', 'system.settings'],
    WRITE: ['customer.manage', 'receivables.manage', 'collections.manage', 'system.settings'],
    CONTROL: ['customer.credit_control', 'receivables.manage', 'system.settings'],
};
function registerCustomerReceivablesIPC(useCases) {
    electron_1.ipcMain.handle('customer.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.update', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.update', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerUpdate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.getById', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getById', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, customerId) => useCases.customerGetById(ctx.companyId, String(customerId || '').trim()))));
    electron_1.ipcMain.handle('customer.list', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.list', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.customerList(ctx.companyId, payload || {}))));
    electron_1.ipcMain.handle('customer.setActive', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.setActive', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerSetActive(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.getContacts', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getContacts', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, customerId) => useCases.customerGetContacts(ctx.companyId, String(customerId || '').trim()))));
    electron_1.ipcMain.handle('customer.saveContact', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.saveContact', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerSaveContact(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.getAddresses', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getAddresses', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, customerId) => useCases.customerGetAddresses(ctx.companyId, String(customerId || '').trim()))));
    electron_1.ipcMain.handle('customer.saveAddress', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.saveAddress', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerSaveAddress(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.getCreditProfile', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getCreditProfile', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, customerId) => useCases.customerGetCreditProfile(ctx.companyId, String(customerId || '').trim()))));
    electron_1.ipcMain.handle('customer.saveCreditProfile', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.saveCreditProfile', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerSaveCreditProfile(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.evaluateCredit', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.evaluateCredit', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL, ...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.customerEvaluateCredit(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('customer.placeHold', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.placeHold', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL] }, async (ctx, _event, payload) => useCases.customerPlaceHold(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.releaseHold', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.releaseHold', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL] }, async (ctx, _event, payload) => useCases.customerReleaseHold(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customer.getExposure', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getExposure', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.customerGetExposure(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('customer.getStatement', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getStatement', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.customerGetStatement(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('customer.getAging', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getAging', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.customerGetAging(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('customer.getTimeline', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customer.getTimeline', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.customerGetTimeline(ctx.companyId, payload || {}))));
    electron_1.ipcMain.handle('customerFollowUp.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customerFollowUp.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerFollowUpCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customerFollowUp.update', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customerFollowUp.update', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerFollowUpUpdate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customerFollowUp.getByCustomer', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customerFollowUp.getByCustomer', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, customerId, includeClosed) => useCases.customerFollowUpGetByCustomer(ctx.companyId, String(customerId || '').trim(), includeClosed))));
    electron_1.ipcMain.handle('customerFollowUp.markDone', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customerFollowUp.markDone', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerFollowUpMarkDone(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('customerFollowUp.cancel', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'customerFollowUp.cancel', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.customerFollowUpCancel(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
}
