"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerManufacturingIPC = registerManufacturingIPC;
const electron_1 = require("electron");
const ipcWrap_1 = require("../core/ipcWrap");
const withGuards_1 = require("./withGuards");
const LEGACY_PERMISSIONS = {
    READ: ['manufacturing.view', 'production.manage', 'system.settings'],
    WRITE: ['manufacturing.create', 'manufacturing.edit', 'production.manage', 'system.settings'],
    POST: ['manufacturing.post', 'DOC.POST', 'production.manage', 'system.settings'],
};
function registerManufacturingIPC(useCases) {
    electron_1.ipcMain.handle('bom.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'bom.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.bomCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('bom.update', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'bom.update', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.bomUpdate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('bom.getById', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'bom.getById', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, bomId) => useCases.bomGetById(ctx.companyId, String(bomId || '').trim()))));
    electron_1.ipcMain.handle('bom.getDefaultForItem', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'bom.getDefaultForItem', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, itemId, asOfDate) => useCases.bomGetDefaultForItem(ctx.companyId, String(itemId || '').trim(), asOfDate || null))));
    electron_1.ipcMain.handle('bom.setDefault', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'bom.setDefault', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, bomId) => useCases.bomSetDefault(ctx.companyId, ctx.branchId, ctx.userId, String(bomId || '').trim()))));
    electron_1.ipcMain.handle('bom.confirm', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'bom.confirm', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, bomId) => useCases.bomConfirm(ctx.companyId, ctx.branchId, ctx.userId, String(bomId || '').trim()))));
    electron_1.ipcMain.handle('bom.cancel', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'bom.cancel', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, bomId) => useCases.bomCancel(ctx.companyId, ctx.branchId, ctx.userId, String(bomId || '').trim()))));
    electron_1.ipcMain.handle('routing.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'routing.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.routingCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('routing.update', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'routing.update', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.routingUpdate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('routing.getById', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'routing.getById', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, routingId) => useCases.routingGetById(ctx.companyId, String(routingId || '').trim()))));
    electron_1.ipcMain.handle('routing.getDefaultForItem', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'routing.getDefaultForItem', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, itemId) => useCases.routingGetDefaultForItem(ctx.companyId, String(itemId || '').trim()))));
    electron_1.ipcMain.handle('routing.setDefault', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'routing.setDefault', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, routingId) => useCases.routingSetDefault(ctx.companyId, ctx.branchId, ctx.userId, String(routingId || '').trim()))));
    electron_1.ipcMain.handle('routing.confirm', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'routing.confirm', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, routingId) => useCases.routingConfirm(ctx.companyId, ctx.branchId, ctx.userId, String(routingId || '').trim()))));
    electron_1.ipcMain.handle('routing.cancel', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'routing.cancel', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, routingId) => useCases.routingCancel(ctx.companyId, ctx.branchId, ctx.userId, String(routingId || '').trim()))));
    electron_1.ipcMain.handle('productionOrder.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionOrderCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('productionOrder.createFromBom', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.createFromBom', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionOrderCreateFromBom(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('productionOrder.update', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.update', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionOrderUpdate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('productionOrder.getById', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.getById', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, orderId) => useCases.productionOrderGetById(ctx.companyId, ctx.branchId, String(orderId || '').trim()))));
    electron_1.ipcMain.handle('productionOrder.release', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.release', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, orderId) => useCases.productionOrderRelease(ctx.companyId, ctx.branchId, ctx.userId, String(orderId || '').trim()))));
    electron_1.ipcMain.handle('productionOrder.cancel', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.cancel', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, orderId) => useCases.productionOrderCancel(ctx.companyId, ctx.branchId, ctx.userId, String(orderId || '').trim()))));
    electron_1.ipcMain.handle('productionOrder.getStatusSummary', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.getStatusSummary', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, orderId) => useCases.productionOrderGetStatusSummary(ctx.companyId, ctx.branchId, String(orderId || '').trim()))));
    electron_1.ipcMain.handle('productionOrder.getCostSummary', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionOrder.getCostSummary', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, orderId) => useCases.productionOrderGetCostSummary(ctx.companyId, ctx.branchId, String(orderId || '').trim()))));
    electron_1.ipcMain.handle('productionIssue.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionIssue.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionIssueCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('productionIssue.getById', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionIssue.getById', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, issueId) => useCases.productionIssueGetById(ctx.companyId, ctx.branchId, String(issueId || '').trim()))));
    electron_1.ipcMain.handle('productionIssue.post', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionIssue.post', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionIssuePost(ctx.companyId, ctx.branchId, ctx.userId, payload || { issueId: '' }))));
    electron_1.ipcMain.handle('productionIssue.cancel', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionIssue.cancel', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionIssueCancel(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('productionReceipt.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionReceipt.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionReceiptCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('productionReceipt.getById', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionReceipt.getById', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, receiptId) => useCases.productionReceiptGetById(ctx.companyId, ctx.branchId, String(receiptId || '').trim()))));
    electron_1.ipcMain.handle('productionReceipt.post', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionReceipt.post', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionReceiptPost(ctx.companyId, ctx.branchId, ctx.userId, payload || { receiptId: '' }))));
    electron_1.ipcMain.handle('productionReceipt.cancel', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'productionReceipt.cancel', legacyPermissions: [...LEGACY_PERMISSIONS.POST, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.productionReceiptCancel(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
}
