"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerVendorPayablesIPC = registerVendorPayablesIPC;
const electron_1 = require("electron");
const ipcWrap_1 = require("../core/ipcWrap");
const withGuards_1 = require("./withGuards");
const LEGACY_PERMISSIONS = {
    READ: ['vendor.view', 'payables.view', 'collections.view', 'system.settings'],
    WRITE: ['vendor.manage', 'payables.manage', 'collections.manage', 'system.settings'],
    CONTROL: ['vendor.payment_control', 'payables.manage', 'system.settings'],
};
function registerVendorPayablesIPC(useCases) {
    electron_1.ipcMain.handle('vendor.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.update', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.update', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorUpdate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getById', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getById', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, vendorId) => useCases.vendorGetById(ctx.companyId, String(vendorId || '').trim()))));
    electron_1.ipcMain.handle('vendor.list', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.list', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.vendorList(ctx.companyId, payload || {}))));
    electron_1.ipcMain.handle('vendor.setActive', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.setActive', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorSetActive(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getContacts', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getContacts', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, vendorId) => useCases.vendorGetContacts(ctx.companyId, String(vendorId || '').trim()))));
    electron_1.ipcMain.handle('vendor.saveContact', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.saveContact', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorSaveContact(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getAddresses', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getAddresses', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, vendorId) => useCases.vendorGetAddresses(ctx.companyId, String(vendorId || '').trim()))));
    electron_1.ipcMain.handle('vendor.saveAddress', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.saveAddress', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorSaveAddress(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getPaymentProfile', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getPaymentProfile', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, vendorId) => useCases.vendorGetPaymentProfile(ctx.companyId, String(vendorId || '').trim()))));
    electron_1.ipcMain.handle('vendor.savePaymentProfile', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.savePaymentProfile', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL, ...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorSavePaymentProfile(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.evaluatePaymentControl', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.evaluatePaymentControl', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL, ...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.vendorEvaluatePaymentControl(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('vendor.placeHold', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.placeHold', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL] }, async (ctx, _event, payload) => useCases.vendorPlaceHold(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.releaseHold', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.releaseHold', legacyPermissions: [...LEGACY_PERMISSIONS.CONTROL] }, async (ctx, _event, payload) => useCases.vendorReleaseHold(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getExposure', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getExposure', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.vendorGetExposure(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getStatement', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getStatement', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.vendorGetStatement(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getAging', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getAging', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.vendorGetAging(ctx.companyId, ctx.branchId, payload || {}))));
    electron_1.ipcMain.handle('vendor.getTimeline', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendor.getTimeline', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, payload) => useCases.vendorGetTimeline(ctx.companyId, payload || {}))));
    electron_1.ipcMain.handle('vendorFollowUp.create', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendorFollowUp.create', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorFollowUpCreate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendorFollowUp.update', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendorFollowUp.update', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorFollowUpUpdate(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendorFollowUp.getByVendor', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendorFollowUp.getByVendor', legacyPermissions: [...LEGACY_PERMISSIONS.READ] }, async (ctx, _event, vendorId, includeClosed) => useCases.vendorFollowUpGetByVendor(ctx.companyId, String(vendorId || '').trim(), includeClosed))));
    electron_1.ipcMain.handle('vendorFollowUp.markDone', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendorFollowUp.markDone', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorFollowUpMarkDone(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
    electron_1.ipcMain.handle('vendorFollowUp.cancel', (0, ipcWrap_1.ipcWrap)((0, withGuards_1.withGuards)({ eventName: 'vendorFollowUp.cancel', legacyPermissions: [...LEGACY_PERMISSIONS.WRITE] }, async (ctx, _event, payload) => useCases.vendorFollowUpCancel(ctx.companyId, ctx.branchId, ctx.userId, payload || {}))));
}
