export type SettingValueType = 'string' | 'number' | 'boolean' | 'select' | 'json' | 'table';
export type SettingInputType =
    | 'text'
    | 'textarea'
    | 'number'
    | 'select'
    | 'toggle'
    | 'checkbox'
    | 'date'
    | 'time'
    | 'password'
    | 'json'
    | 'table';

export type SettingOptionSeed = {
    value: string;
    labelAr: string;
    labelEn: string;
};

export type SettingGroupSeed = {
    code: string;
    nameAr: string;
    nameEn: string;
    descriptionAr?: string;
    descriptionEn?: string;
    sortOrder: number;
};

export type SettingDefinitionSeed = {
    key: string;
    groupCode: string;
    labelAr: string;
    labelEn: string;
    descriptionAr?: string;
    descriptionEn?: string;
    valueType: SettingValueType;
    inputType: SettingInputType;
    defaultValue: unknown;
    options?: SettingOptionSeed[];
    validation?: Record<string, unknown>;
    scope?: 'system' | 'company' | 'branch' | 'user';
    sortOrder?: number;
    isRequired?: boolean;
    isSensitive?: boolean;
    needsReview?: boolean;
    metadata?: Record<string, unknown>;
};

const yesNo = [
    { value: 'true', labelAr: 'نعم', labelEn: 'Yes' },
    { value: 'false', labelAr: 'لا', labelEn: 'No' },
];

const languages = [
    { value: 'ar', labelAr: 'العربية', labelEn: 'Arabic' },
    { value: 'en', labelAr: 'الإنجليزية', labelEn: 'English' },
    { value: 'he', labelAr: 'العبرية', labelEn: 'Hebrew' },
];

const currencies = [
    { value: 'ILS', labelAr: 'شيكل ILS', labelEn: 'Israeli Shekel' },
    { value: 'USD', labelAr: 'دولار USD', labelEn: 'US Dollar' },
    { value: 'JOD', labelAr: 'دينار JOD', labelEn: 'Jordanian Dinar' },
    { value: 'EUR', labelAr: 'يورو EUR', labelEn: 'Euro' },
];

const tableColumns = (columns: Array<{ key: string; labelAr: string; labelEn: string }>) => ({
    tableColumns: columns,
});

export const DEFAULT_SETTING_GROUPS: SettingGroupSeed[] = [
    { code: 'company_information', nameAr: 'معلومات الشركة', nameEn: 'Company Information', sortOrder: 10 },
    { code: 'general', nameAr: 'عام', nameEn: 'General', sortOrder: 20 },
    { code: 'features', nameAr: 'خصائص', nameEn: 'Features', sortOrder: 30 },
    { code: 'manual_vouchers', nameAr: 'السندات اليدوية', nameEn: 'Manual Vouchers', sortOrder: 40 },
    { code: 'currency', nameAr: 'العملة', nameEn: 'Currency', sortOrder: 50 },
    { code: 'bank_reconciliation', nameAr: 'تسوية البنك', nameEn: 'Bank Reconciliation', sortOrder: 60 },
    { code: 'financial_reports', nameAr: 'التقارير المالية', nameEn: 'Financial Reports', sortOrder: 70 },
    { code: 'data_entry', nameAr: 'إدخال البيانات', nameEn: 'Data Entry', sortOrder: 80 },
    { code: 'active_periods', nameAr: 'الفترات الفعالة', nameEn: 'Active Periods', sortOrder: 90 },
    { code: 'inventory', nameAr: 'المخزون', nameEn: 'Inventory', sortOrder: 100 },
    { code: 'warehouses', nameAr: 'المستودعات', nameEn: 'Warehouses', sortOrder: 110 },
    { code: 'production', nameAr: 'الإنتاج', nameEn: 'Production', sortOrder: 120 },
    { code: 'fixed_assets', nameAr: 'الموجودات الثابتة', nameEn: 'Fixed Assets', sortOrder: 130 },
    { code: 'tax', nameAr: 'الضريبة', nameEn: 'Tax', sortOrder: 140 },
    { code: 'payroll', nameAr: 'الرواتب', nameEn: 'Payroll', sortOrder: 150 },
    { code: 'display_printing', nameAr: 'الإظهار والطباعة', nameEn: 'Display & Printing', sortOrder: 160 },
    { code: 'sales_purchase_documents', nameAr: 'مستندات المبيعات / المشتريات', nameEn: 'Sales / Purchase Documents', sortOrder: 170 },
    { code: 'inventory_display_printing', nameAr: 'إظهار وطباعة المخزون', nameEn: 'Inventory Display & Printing', sortOrder: 180 },
    { code: 'defaults', nameAr: 'القيم الافتراضية', nameEn: 'Defaults', sortOrder: 190 },
    { code: 'html_templates', nameAr: 'نماذج HTML', nameEn: 'HTML Templates', sortOrder: 200 },
    { code: 'header_name_address', nameAr: 'الترويسة / اسم وعنوان', nameEn: 'Header / Name & Address', sortOrder: 210 },
    { code: 'footer', nameAr: 'التذييل', nameEn: 'Footer', sortOrder: 220 },
    { code: 'customer_balance_print_format', nameAr: 'تنسيق طباعة رصيد الزبون', nameEn: 'Customer Balance Print Format', sortOrder: 230 },
    { code: 'employee_attendance_error_template', nameAr: 'نموذج أخطاء الدوام للموظف', nameEn: 'Employee Attendance Error Template', sortOrder: 240 },
    { code: 'bills_of_exchange', nameAr: 'كمبيالات', nameEn: 'Bills of Exchange', sortOrder: 250 },
    { code: 'sms_templates', nameAr: 'نماذج الرسائل القصيرة SMS', nameEn: 'SMS Templates', sortOrder: 260 },
    { code: 'sms_creditor', nameAr: 'رسالة قصيرة للدائن', nameEn: 'Creditor SMS', sortOrder: 270 },
    { code: 'sms_debtor', nameAr: 'رسالة قصيرة للمدين', nameEn: 'Debtor SMS', sortOrder: 280 },
    { code: 'customer_balance', nameAr: 'رصيد الزبون', nameEn: 'Customer Balance', sortOrder: 290 },
    { code: 'bisan_services_api', nameAr: 'إعدادات خدمات بيسان / API', nameEn: 'Bisan Services / API', sortOrder: 300 },
    { code: 'security', nameAr: 'الحماية', nameEn: 'Security', sortOrder: 310 },
    { code: 'timezone', nameAr: 'إعدادات المنطقة الزمنية', nameEn: 'Timezone Settings', sortOrder: 320 },
];

export const DEFAULT_SETTINGS: SettingDefinitionSeed[] = [
    {
        key: 'company_name_ar',
        groupCode: 'company_information',
        labelAr: 'اسم الشركة عربي',
        labelEn: 'Company Name Arabic',
        valueType: 'string',
        inputType: 'text',
        defaultValue: 'WAFI ERP',
        isRequired: true,
        sortOrder: 10,
    },
    {
        key: 'company_name_en',
        groupCode: 'company_information',
        labelAr: 'اسم الشركة إنجليزي',
        labelEn: 'Company Name English',
        valueType: 'string',
        inputType: 'text',
        defaultValue: 'WAFI ERP',
        sortOrder: 20,
    },
    {
        key: 'tax_id',
        groupCode: 'company_information',
        labelAr: 'الرقم الضريبي',
        labelEn: 'Tax ID',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        validation: { maxLength: 60 },
        sortOrder: 30,
    },
    {
        key: 'address',
        groupCode: 'company_information',
        labelAr: 'العنوان',
        labelEn: 'Address',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: '',
        sortOrder: 40,
    },
    {
        key: 'phone',
        groupCode: 'company_information',
        labelAr: 'الهاتف',
        labelEn: 'Phone',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        sortOrder: 50,
    },
    {
        key: 'email',
        groupCode: 'company_information',
        labelAr: 'البريد الإلكتروني',
        labelEn: 'Email',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        validation: { pattern: '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$' },
        sortOrder: 60,
    },
    {
        key: 'website',
        groupCode: 'company_information',
        labelAr: 'الموقع الإلكتروني',
        labelEn: 'Website',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        sortOrder: 70,
    },
    {
        key: 'currency_symbol',
        groupCode: 'company_information',
        labelAr: 'العملة الأساسية',
        labelEn: 'Base Currency',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ILS',
        options: currencies,
        isRequired: true,
        sortOrder: 80,
    },
    {
        key: 'logo_url',
        groupCode: 'company_information',
        labelAr: 'رابط شعار الشركة',
        labelEn: 'Company Logo URL',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        sortOrder: 90,
    },
    {
        key: 'companyName',
        groupCode: 'company_information',
        labelAr: 'اسم الشركة المختصر',
        labelEn: 'Short Company Name',
        valueType: 'string',
        inputType: 'text',
        defaultValue: 'WAFI ERP User',
        metadata: { legacyKey: true },
        sortOrder: 100,
    },
    {
        key: 'general.language',
        groupCode: 'general',
        labelAr: 'لغة الواجهة الافتراضية',
        labelEn: 'Default UI Language',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ar',
        options: languages,
        isRequired: true,
        sortOrder: 10,
    },
    {
        key: 'general.rtl_enabled',
        groupCode: 'general',
        labelAr: 'تفعيل اتجاه RTL',
        labelEn: 'Enable RTL Layout',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 20,
    },
    {
        key: 'general.date_format',
        groupCode: 'general',
        labelAr: 'تنسيق التاريخ',
        labelEn: 'Date Format',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'yyyy-MM-dd',
        options: [
            { value: 'yyyy-MM-dd', labelAr: '2026-04-26', labelEn: 'YYYY-MM-DD' },
            { value: 'dd/MM/yyyy', labelAr: '26/04/2026', labelEn: 'DD/MM/YYYY' },
            { value: 'MM/dd/yyyy', labelAr: '04/26/2026', labelEn: 'MM/DD/YYYY' },
        ],
        sortOrder: 30,
    },
    {
        key: 'general.decimal_places',
        groupCode: 'general',
        labelAr: 'عدد المنازل العشرية',
        labelEn: 'Decimal Places',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 2,
        validation: { min: 0, max: 6 },
        sortOrder: 40,
    },
    {
        key: 'general.show_branch_selector',
        groupCode: 'general',
        labelAr: 'إظهار اختيار الفرع',
        labelEn: 'Show Branch Selector',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 50,
    },
    {
        key: 'features.sales_enabled',
        groupCode: 'features',
        labelAr: 'تفعيل المبيعات',
        labelEn: 'Enable Sales',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 10,
    },
    {
        key: 'features.purchases_enabled',
        groupCode: 'features',
        labelAr: 'تفعيل المشتريات',
        labelEn: 'Enable Purchases',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 20,
    },
    {
        key: 'features.manufacturing_enabled',
        groupCode: 'features',
        labelAr: 'تفعيل التصنيع',
        labelEn: 'Enable Manufacturing',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 30,
    },
    {
        key: 'features.feature_matrix',
        groupCode: 'features',
        labelAr: 'جدول الخصائص حسب النسخة',
        labelEn: 'Edition Feature Matrix',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { feature: 'POS', edition: 'Trade', enabled: 'true' },
            { feature: 'Manufacturing', edition: 'Manufacturing', enabled: 'true' },
        ],
        metadata: tableColumns([
            { key: 'feature', labelAr: 'الخاصية', labelEn: 'Feature' },
            { key: 'edition', labelAr: 'النسخة', labelEn: 'Edition' },
            { key: 'enabled', labelAr: 'مفعلة', labelEn: 'Enabled' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'manual_vouchers.allow_manual_numbers',
        groupCode: 'manual_vouchers',
        labelAr: 'السماح بأرقام سندات يدوية',
        labelEn: 'Allow Manual Voucher Numbers',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 10,
    },
    {
        key: 'manual_vouchers.numbering_mode',
        groupCode: 'manual_vouchers',
        labelAr: 'طريقة ترقيم السندات',
        labelEn: 'Voucher Numbering Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'AUTO',
        options: [
            { value: 'AUTO', labelAr: 'تلقائي', labelEn: 'Automatic' },
            { value: 'MANUAL', labelAr: 'يدوي', labelEn: 'Manual' },
            { value: 'HYBRID', labelAr: 'تلقائي مع تعديل', labelEn: 'Hybrid' },
        ],
        sortOrder: 20,
    },
    {
        key: 'manual_vouchers.require_manual_reason',
        groupCode: 'manual_vouchers',
        labelAr: 'طلب سبب عند تغيير رقم السند',
        labelEn: 'Require Reason on Manual Number Change',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 30,
    },
    {
        key: 'manual_vouchers.prefixes',
        groupCode: 'manual_vouchers',
        labelAr: 'بادئات السندات',
        labelEn: 'Voucher Prefixes',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { type: 'JV', prefix: 'JV', nextNo: '1' },
            { type: 'PV', prefix: 'PV', nextNo: '1' },
            { type: 'RV', prefix: 'RV', nextNo: '1' },
        ],
        metadata: tableColumns([
            { key: 'type', labelAr: 'النوع', labelEn: 'Type' },
            { key: 'prefix', labelAr: 'البادئة', labelEn: 'Prefix' },
            { key: 'nextNo', labelAr: 'الرقم التالي', labelEn: 'Next No.' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'currency',
        groupCode: 'currency',
        labelAr: 'العملة الافتراضية القديمة',
        labelEn: 'Legacy Currency',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ILS',
        options: currencies,
        metadata: { legacyKey: true },
        sortOrder: 5,
    },
    {
        key: 'currency.base_currency',
        groupCode: 'currency',
        labelAr: 'العملة الأساسية',
        labelEn: 'Base Currency',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ILS',
        options: currencies,
        sortOrder: 10,
    },
    {
        key: 'currency.rate_source',
        groupCode: 'currency',
        labelAr: 'مصدر سعر الصرف',
        labelEn: 'Exchange Rate Source',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'MANUAL',
        options: [
            { value: 'MANUAL', labelAr: 'يدوي', labelEn: 'Manual' },
            { value: 'BANK_OF_ISRAEL', labelAr: 'بنك إسرائيل', labelEn: 'Bank of Israel' },
            { value: 'API', labelAr: 'خدمة API', labelEn: 'API' },
        ],
        sortOrder: 20,
    },
    {
        key: 'currency.auto_update_rates',
        groupCode: 'currency',
        labelAr: 'تحديث أسعار العملات تلقائياً',
        labelEn: 'Auto Update Exchange Rates',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        sortOrder: 30,
    },
    {
        key: 'currency.allowed_currencies',
        groupCode: 'currency',
        labelAr: 'العملات المسموحة',
        labelEn: 'Allowed Currencies',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { code: 'ILS', name: 'شيكل', enabled: 'true' },
            { code: 'USD', name: 'دولار', enabled: 'true' },
            { code: 'JOD', name: 'دينار', enabled: 'true' },
        ],
        metadata: tableColumns([
            { key: 'code', labelAr: 'الكود', labelEn: 'Code' },
            { key: 'name', labelAr: 'الاسم', labelEn: 'Name' },
            { key: 'enabled', labelAr: 'مفعلة', labelEn: 'Enabled' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'bank_reconciliation.match_tolerance',
        groupCode: 'bank_reconciliation',
        labelAr: 'هامش مطابقة المبلغ',
        labelEn: 'Amount Match Tolerance',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 0.01,
        validation: { min: 0, max: 999999 },
        sortOrder: 10,
    },
    {
        key: 'bank_reconciliation.auto_match',
        groupCode: 'bank_reconciliation',
        labelAr: 'تفعيل المطابقة الآلية',
        labelEn: 'Enable Auto Match',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 20,
    },
    {
        key: 'bank_reconciliation.statement_date_format',
        groupCode: 'bank_reconciliation',
        labelAr: 'تنسيق تاريخ كشف البنك',
        labelEn: 'Statement Date Format',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'yyyy-MM-dd',
        options: [
            { value: 'yyyy-MM-dd', labelAr: 'YYYY-MM-DD', labelEn: 'YYYY-MM-DD' },
            { value: 'dd/MM/yyyy', labelAr: 'DD/MM/YYYY', labelEn: 'DD/MM/YYYY' },
        ],
        sortOrder: 30,
    },
    {
        key: 'bank_reconciliation.unmatched_action',
        groupCode: 'bank_reconciliation',
        labelAr: 'إجراء الحركات غير المطابقة',
        labelEn: 'Unmatched Transactions Action',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'KEEP_OPEN',
        options: [
            { value: 'KEEP_OPEN', labelAr: 'إبقاء مفتوحة', labelEn: 'Keep Open' },
            { value: 'CREATE_ADJUSTMENT', labelAr: 'إنشاء تسوية', labelEn: 'Create Adjustment' },
            { value: 'REVIEW_QUEUE', labelAr: 'إرسال للمراجعة', labelEn: 'Review Queue' },
        ],
        sortOrder: 40,
    },
    {
        key: 'financial_reports.default_level',
        groupCode: 'financial_reports',
        labelAr: 'مستوى الحساب الافتراضي',
        labelEn: 'Default Account Level',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 4,
        validation: { min: 1, max: 10 },
        sortOrder: 10,
    },
    {
        key: 'financial_reports.show_zero_balances',
        groupCode: 'financial_reports',
        labelAr: 'إظهار الأرصدة الصفرية',
        labelEn: 'Show Zero Balances',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'financial_reports.comparative_period',
        groupCode: 'financial_reports',
        labelAr: 'فترة المقارنة الافتراضية',
        labelEn: 'Default Comparative Period',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'NONE',
        options: [
            { value: 'NONE', labelAr: 'بدون مقارنة', labelEn: 'None' },
            { value: 'PREVIOUS_PERIOD', labelAr: 'الفترة السابقة', labelEn: 'Previous Period' },
            { value: 'PREVIOUS_YEAR', labelAr: 'السنة السابقة', labelEn: 'Previous Year' },
        ],
        sortOrder: 30,
    },
    {
        key: 'financial_reports.report_footer_note',
        groupCode: 'financial_reports',
        labelAr: 'ملاحظة تذييل التقارير',
        labelEn: 'Report Footer Note',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: '',
        sortOrder: 40,
    },
    {
        key: 'data_entry.autosave_enabled',
        groupCode: 'data_entry',
        labelAr: 'حفظ تلقائي أثناء الإدخال',
        labelEn: 'Autosave While Entering Data',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        sortOrder: 10,
    },
    {
        key: 'data_entry.duplicate_warning',
        groupCode: 'data_entry',
        labelAr: 'تنبيه عند التكرار',
        labelEn: 'Duplicate Warning',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 20,
    },
    {
        key: 'data_entry.required_cost_center_mode',
        groupCode: 'data_entry',
        labelAr: 'إلزام مركز التكلفة',
        labelEn: 'Cost Center Required Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'OPTIONAL',
        options: [
            { value: 'OPTIONAL', labelAr: 'اختياري', labelEn: 'Optional' },
            { value: 'EXPENSES_ONLY', labelAr: 'على المصاريف فقط', labelEn: 'Expenses Only' },
            { value: 'ALL_LINES', labelAr: 'على كل السطور', labelEn: 'All Lines' },
        ],
        sortOrder: 30,
    },
    {
        key: 'data_entry.default_notes',
        groupCode: 'data_entry',
        labelAr: 'ملاحظات افتراضية',
        labelEn: 'Default Notes',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        sortOrder: 40,
    },
    {
        key: 'active_periods.allow_posting_closed_period',
        groupCode: 'active_periods',
        labelAr: 'السماح بالترحيل في فترة مغلقة',
        labelEn: 'Allow Posting in Closed Period',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 10,
    },
    {
        key: 'active_periods.lock_mode',
        groupCode: 'active_periods',
        labelAr: 'طريقة قفل الفترة',
        labelEn: 'Period Lock Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'MONTHLY',
        options: [
            { value: 'MONTHLY', labelAr: 'شهري', labelEn: 'Monthly' },
            { value: 'QUARTERLY', labelAr: 'ربع سنوي', labelEn: 'Quarterly' },
            { value: 'YEARLY', labelAr: 'سنوي', labelEn: 'Yearly' },
        ],
        sortOrder: 20,
    },
    {
        key: 'active_periods.table',
        groupCode: 'active_periods',
        labelAr: 'جدول الفترات الفعالة',
        labelEn: 'Active Periods Table',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { period: '2026-01', status: 'OPEN', closingUser: '' },
            { period: '2026-02', status: 'OPEN', closingUser: '' },
        ],
        metadata: tableColumns([
            { key: 'period', labelAr: 'الفترة', labelEn: 'Period' },
            { key: 'status', labelAr: 'الحالة', labelEn: 'Status' },
            { key: 'closingUser', labelAr: 'مستخدم الإغلاق', labelEn: 'Closing User' },
        ]),
        sortOrder: 30,
    },
    {
        key: 'INVENTORY_COSTING_METHOD',
        groupCode: 'inventory',
        labelAr: 'طريقة تقييم المخزون',
        labelEn: 'Inventory Costing Method',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'WAC',
        options: [
            { value: 'WAC', labelAr: 'المتوسط المرجح', labelEn: 'Weighted Average' },
            { value: 'FIFO', labelAr: 'الوارد أولاً صادر أولاً', labelEn: 'FIFO' },
            { value: 'LIFO', labelAr: 'الوارد أخيراً صادر أولاً', labelEn: 'LIFO' },
            { value: 'LPP', labelAr: 'آخر سعر شراء', labelEn: 'Last Purchase Price' },
        ],
        metadata: { legacyKey: true },
        sortOrder: 5,
    },
    {
        key: 'inventory.perpetual',
        groupCode: 'inventory',
        labelAr: 'نظام الجرد المستمر',
        labelEn: 'Perpetual Inventory',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 10,
    },
    {
        key: 'inventory.allow_negative_stock',
        groupCode: 'inventory',
        labelAr: 'السماح بالمخزون السالب',
        labelEn: 'Allow Negative Stock',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'inventory.default_unit',
        groupCode: 'inventory',
        labelAr: 'الوحدة الافتراضية',
        labelEn: 'Default Unit',
        valueType: 'string',
        inputType: 'text',
        defaultValue: 'PCS',
        sortOrder: 30,
    },
    {
        key: 'inventory.batch_tracking',
        groupCode: 'inventory',
        labelAr: 'تتبع الدُفعات',
        labelEn: 'Batch Tracking',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        sortOrder: 40,
    },
    {
        key: 'warehouses.default_warehouse',
        groupCode: 'warehouses',
        labelAr: 'المستودع الافتراضي',
        labelEn: 'Default Warehouse',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        sortOrder: 10,
    },
    {
        key: 'warehouses.require_bin_location',
        groupCode: 'warehouses',
        labelAr: 'إلزام موقع التخزين',
        labelEn: 'Require Bin Location',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'warehouses.transfer_approval_mode',
        groupCode: 'warehouses',
        labelAr: 'اعتماد النقل بين المستودعات',
        labelEn: 'Warehouse Transfer Approval',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'OPTIONAL',
        options: [
            { value: 'NONE', labelAr: 'بدون اعتماد', labelEn: 'No Approval' },
            { value: 'OPTIONAL', labelAr: 'اختياري', labelEn: 'Optional' },
            { value: 'REQUIRED', labelAr: 'إلزامي', labelEn: 'Required' },
        ],
        sortOrder: 30,
    },
    {
        key: 'warehouses.settings_table',
        groupCode: 'warehouses',
        labelAr: 'إعدادات المستودعات',
        labelEn: 'Warehouse Settings Table',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [{ warehouseCode: 'MAIN', allowSales: 'true', allowPurchases: 'true' }],
        metadata: tableColumns([
            { key: 'warehouseCode', labelAr: 'كود المستودع', labelEn: 'Warehouse Code' },
            { key: 'allowSales', labelAr: 'مبيعات', labelEn: 'Sales' },
            { key: 'allowPurchases', labelAr: 'مشتريات', labelEn: 'Purchases' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'manufacturing.issue.accounting',
        groupCode: 'production',
        labelAr: 'محاسبة صرف المواد',
        labelEn: 'Material Issue Accounting',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'POST',
        options: [
            { value: 'POST', labelAr: 'ترحيل محاسبي', labelEn: 'Post Accounting' },
            { value: 'NONE', labelAr: 'بدون ترحيل', labelEn: 'No Posting' },
        ],
        sortOrder: 10,
    },
    {
        key: 'manufacturing.receipt.accounting',
        groupCode: 'production',
        labelAr: 'محاسبة استلام الإنتاج',
        labelEn: 'Production Receipt Accounting',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'POST',
        options: [
            { value: 'POST', labelAr: 'ترحيل محاسبي', labelEn: 'Post Accounting' },
            { value: 'NONE', labelAr: 'بدون ترحيل', labelEn: 'No Posting' },
        ],
        sortOrder: 20,
    },
    {
        key: 'manufacturing.allow_over_issue',
        groupCode: 'production',
        labelAr: 'السماح بصرف أكثر من المخطط',
        labelEn: 'Allow Over Issue',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 30,
    },
    {
        key: 'manufacturing.allow_over_receipt',
        groupCode: 'production',
        labelAr: 'السماح باستلام أكثر من المخطط',
        labelEn: 'Allow Over Receipt',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 40,
    },
    {
        key: 'production.work_centers_template',
        groupCode: 'production',
        labelAr: 'جدول مراكز العمل الافتراضية',
        labelEn: 'Default Work Centers Table',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [{ code: 'WC-01', name: 'مركز إنتاج رئيسي', capacity: '8' }],
        metadata: tableColumns([
            { key: 'code', labelAr: 'الكود', labelEn: 'Code' },
            { key: 'name', labelAr: 'الاسم', labelEn: 'Name' },
            { key: 'capacity', labelAr: 'السعة اليومية', labelEn: 'Daily Capacity' },
        ]),
        sortOrder: 50,
    },
    {
        key: 'fixed_assets.depreciation_method',
        groupCode: 'fixed_assets',
        labelAr: 'طريقة الإهلاك الافتراضية',
        labelEn: 'Default Depreciation Method',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'STRAIGHT_LINE',
        options: [
            { value: 'STRAIGHT_LINE', labelAr: 'القسط الثابت', labelEn: 'Straight Line' },
            { value: 'DECLINING_BALANCE', labelAr: 'القسط المتناقص', labelEn: 'Declining Balance' },
        ],
        sortOrder: 10,
    },
    {
        key: 'fixed_assets.capitalization_threshold',
        groupCode: 'fixed_assets',
        labelAr: 'حد الرسملة',
        labelEn: 'Capitalization Threshold',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 0,
        validation: { min: 0 },
        sortOrder: 20,
    },
    {
        key: 'fixed_assets.require_asset_tag',
        groupCode: 'fixed_assets',
        labelAr: 'إلزام رقم الأصل',
        labelEn: 'Require Asset Tag',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 30,
    },
    {
        key: 'fixed_assets.asset_classes',
        groupCode: 'fixed_assets',
        labelAr: 'جدول مجموعات الأصول',
        labelEn: 'Asset Classes Table',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { code: 'VEH', name: 'سيارات', rate: '20' },
            { code: 'COMP', name: 'حاسوب', rate: '25' },
        ],
        metadata: tableColumns([
            { key: 'code', labelAr: 'الكود', labelEn: 'Code' },
            { key: 'name', labelAr: 'الاسم', labelEn: 'Name' },
            { key: 'rate', labelAr: 'نسبة الإهلاك', labelEn: 'Depreciation Rate' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'VAT_RATE',
        groupCode: 'tax',
        labelAr: 'نسبة ضريبة القيمة المضافة',
        labelEn: 'VAT Rate',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 16,
        validation: { min: 0, max: 100 },
        metadata: { legacyKey: true },
        sortOrder: 10,
    },
    {
        key: 'taxRate',
        groupCode: 'tax',
        labelAr: 'نسبة الضريبة القديمة',
        labelEn: 'Legacy Tax Rate',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 16,
        validation: { min: 0, max: 100 },
        metadata: { legacyKey: true },
        sortOrder: 15,
    },
    {
        key: 'tax.registration_number',
        groupCode: 'tax',
        labelAr: 'رقم التسجيل الضريبي',
        labelEn: 'Tax Registration Number',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        sortOrder: 20,
    },
    {
        key: 'tax.invoice_mode',
        groupCode: 'tax',
        labelAr: 'نمط الفاتورة الضريبية',
        labelEn: 'Tax Invoice Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'STANDARD',
        options: [
            { value: 'STANDARD', labelAr: 'قياسي', labelEn: 'Standard' },
            { value: 'SIMPLIFIED', labelAr: 'مبسط', labelEn: 'Simplified' },
            { value: 'EXEMPT', labelAr: 'معفى', labelEn: 'Exempt' },
        ],
        sortOrder: 30,
    },
    {
        key: 'tax.withholding_enabled',
        groupCode: 'tax',
        labelAr: 'تفعيل خصم المصدر',
        labelEn: 'Enable Withholding Tax',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        sortOrder: 40,
    },
    {
        key: 'tax.tax_profiles',
        groupCode: 'tax',
        labelAr: 'شرائح الضريبة',
        labelEn: 'Tax Profiles',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [{ code: 'VAT16', name: 'VAT 16%', rate: '16', active: 'true' }],
        metadata: tableColumns([
            { key: 'code', labelAr: 'الكود', labelEn: 'Code' },
            { key: 'name', labelAr: 'الاسم', labelEn: 'Name' },
            { key: 'rate', labelAr: 'النسبة', labelEn: 'Rate' },
            { key: 'active', labelAr: 'فعال', labelEn: 'Active' },
        ]),
        sortOrder: 50,
    },
    {
        key: 'payroll.salary_currency',
        groupCode: 'payroll',
        labelAr: 'عملة الرواتب',
        labelEn: 'Payroll Currency',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ILS',
        options: currencies,
        sortOrder: 10,
    },
    {
        key: 'payroll.month_close_mode',
        groupCode: 'payroll',
        labelAr: 'طريقة إغلاق شهر الرواتب',
        labelEn: 'Payroll Month Close Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'MANUAL',
        options: [
            { value: 'MANUAL', labelAr: 'يدوي', labelEn: 'Manual' },
            { value: 'AFTER_POSTING', labelAr: 'بعد الترحيل', labelEn: 'After Posting' },
        ],
        sortOrder: 20,
    },
    {
        key: 'payroll.include_overtime',
        groupCode: 'payroll',
        labelAr: 'احتساب العمل الإضافي',
        labelEn: 'Include Overtime',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 30,
    },
    {
        key: 'payroll.attendance_integration',
        groupCode: 'payroll',
        labelAr: 'ربط الرواتب بالدوام',
        labelEn: 'Attendance Integration',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 40,
    },
    {
        key: 'printer',
        groupCode: 'display_printing',
        labelAr: 'الطابعة الافتراضية',
        labelEn: 'Default Printer',
        valueType: 'string',
        inputType: 'text',
        defaultValue: 'Default',
        metadata: { legacyKey: true },
        sortOrder: 5,
    },
    {
        key: 'display_printing.theme',
        groupCode: 'display_printing',
        labelAr: 'نمط العرض',
        labelEn: 'Theme',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'LIGHT',
        options: [
            { value: 'LIGHT', labelAr: 'فاتح', labelEn: 'Light' },
            { value: 'DARK', labelAr: 'داكن', labelEn: 'Dark' },
            { value: 'SYSTEM', labelAr: 'حسب النظام', labelEn: 'System' },
        ],
        sortOrder: 10,
    },
    {
        key: 'display_printing.paper_size',
        groupCode: 'display_printing',
        labelAr: 'حجم الورق',
        labelEn: 'Paper Size',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'A4',
        options: [
            { value: 'A4', labelAr: 'A4', labelEn: 'A4' },
            { value: 'A5', labelAr: 'A5', labelEn: 'A5' },
            { value: 'POS80', labelAr: 'حراري 80mm', labelEn: 'POS 80mm' },
        ],
        sortOrder: 20,
    },
    {
        key: 'display_printing.preview_before_print',
        groupCode: 'display_printing',
        labelAr: 'معاينة قبل الطباعة',
        labelEn: 'Preview Before Print',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 30,
    },
    {
        key: 'display_printing.default_copies',
        groupCode: 'display_printing',
        labelAr: 'عدد النسخ الافتراضي',
        labelEn: 'Default Copies',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 1,
        validation: { min: 1, max: 9 },
        sortOrder: 40,
    },
    {
        key: 'sales.delivery.cogs_posting_mode',
        groupCode: 'sales_purchase_documents',
        labelAr: 'ترحيل تكلفة بضاعة المبيعات',
        labelEn: 'Sales COGS Posting Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'INVOICE',
        options: [
            { value: 'INVOICE', labelAr: 'عند الفاتورة', labelEn: 'At Invoice' },
            { value: 'DELIVERY', labelAr: 'عند الإرسالية', labelEn: 'At Delivery' },
        ],
        sortOrder: 10,
    },
    {
        key: 'sales.allow_over_delivery',
        groupCode: 'sales_purchase_documents',
        labelAr: 'السماح بتسليم أكثر من الطلب',
        labelEn: 'Allow Over Delivery',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'sales.allow_over_return',
        groupCode: 'sales_purchase_documents',
        labelAr: 'السماح بمردودات مبيعات أكبر من الأصل',
        labelEn: 'Allow Over Sales Return',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 30,
    },
    {
        key: 'sales.return_cost_reversal',
        groupCode: 'sales_purchase_documents',
        labelAr: 'عكس تكلفة مردودات المبيعات',
        labelEn: 'Reverse Sales Return Cost',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 40,
    },
    {
        key: 'purchase.grn.accounting_mode',
        groupCode: 'sales_purchase_documents',
        labelAr: 'محاسبة استلام المشتريات',
        labelEn: 'GRN Accounting Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'INVOICE',
        options: [
            { value: 'INVOICE', labelAr: 'عند الفاتورة', labelEn: 'At Invoice' },
            { value: 'RECEIPT', labelAr: 'عند الاستلام', labelEn: 'At Receipt' },
        ],
        sortOrder: 50,
    },
    {
        key: 'purchase.allow_over_receipt',
        groupCode: 'sales_purchase_documents',
        labelAr: 'السماح باستلام أكثر من أمر الشراء',
        labelEn: 'Allow Over Receipt',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 60,
    },
    {
        key: 'purchase.allow_over_return',
        groupCode: 'sales_purchase_documents',
        labelAr: 'السماح بمردودات مشتريات أكبر من الأصل',
        labelEn: 'Allow Over Purchase Return',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 70,
    },
    {
        key: 'purchase.return.financial_impact',
        groupCode: 'sales_purchase_documents',
        labelAr: 'الأثر المالي لمردودات المشتريات',
        labelEn: 'Purchase Return Financial Impact',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 80,
    },
    {
        key: 'sales_purchase_documents.numbering',
        groupCode: 'sales_purchase_documents',
        labelAr: 'ترقيم مستندات البيع والشراء',
        labelEn: 'Sales/Purchase Document Numbering',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { document: 'Sales Invoice', prefix: 'SI', nextNo: '1' },
            { document: 'Purchase Invoice', prefix: 'PI', nextNo: '1' },
        ],
        metadata: tableColumns([
            { key: 'document', labelAr: 'المستند', labelEn: 'Document' },
            { key: 'prefix', labelAr: 'البادئة', labelEn: 'Prefix' },
            { key: 'nextNo', labelAr: 'الرقم التالي', labelEn: 'Next No.' },
        ]),
        sortOrder: 90,
    },
    {
        key: 'inventory_display_printing.barcode_size',
        groupCode: 'inventory_display_printing',
        labelAr: 'حجم الباركود',
        labelEn: 'Barcode Size',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'MEDIUM',
        options: [
            { value: 'SMALL', labelAr: 'صغير', labelEn: 'Small' },
            { value: 'MEDIUM', labelAr: 'متوسط', labelEn: 'Medium' },
            { value: 'LARGE', labelAr: 'كبير', labelEn: 'Large' },
        ],
        sortOrder: 10,
    },
    {
        key: 'inventory_display_printing.show_cost',
        groupCode: 'inventory_display_printing',
        labelAr: 'إظهار التكلفة في تقارير المخزون',
        labelEn: 'Show Cost in Inventory Reports',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'inventory_display_printing.report_language',
        groupCode: 'inventory_display_printing',
        labelAr: 'لغة تقارير المخزون',
        labelEn: 'Inventory Report Language',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ar',
        options: languages,
        sortOrder: 30,
    },
    {
        key: 'inventory_display_printing.label_columns',
        groupCode: 'inventory_display_printing',
        labelAr: 'عدد أعمدة الملصقات',
        labelEn: 'Label Columns',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 2,
        validation: { min: 1, max: 5 },
        sortOrder: 40,
    },
    {
        key: 'DEFAULT_SALES_REVENUE_ACCOUNT_ID',
        groupCode: 'defaults',
        labelAr: 'حساب إيرادات المبيعات الافتراضي',
        labelEn: 'Default Sales Revenue Account',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        metadata: { legacyKey: true },
        sortOrder: 10,
    },
    {
        key: 'DEFAULT_SALES_TAX_ACCOUNT_ID',
        groupCode: 'defaults',
        labelAr: 'حساب ضريبة المبيعات الافتراضي',
        labelEn: 'Default Sales Tax Account',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        metadata: { legacyKey: true },
        sortOrder: 20,
    },
    {
        key: 'DEFAULT_PURCHASES_TAX_ACCOUNT_ID',
        groupCode: 'defaults',
        labelAr: 'حساب ضريبة المشتريات الافتراضي',
        labelEn: 'Default Purchases Tax Account',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        metadata: { legacyKey: true },
        sortOrder: 30,
    },
    {
        key: 'DEFAULT_INVENTORY_ACCOUNT_ID',
        groupCode: 'defaults',
        labelAr: 'حساب المخزون الافتراضي',
        labelEn: 'Default Inventory Account',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        metadata: { legacyKey: true },
        sortOrder: 40,
    },
    {
        key: 'DEFAULT_COGS_ACCOUNT_ID',
        groupCode: 'defaults',
        labelAr: 'حساب تكلفة البضاعة المباعة',
        labelEn: 'Default COGS Account',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        metadata: { legacyKey: true },
        sortOrder: 50,
    },
    {
        key: 'defaults.default_payment_method',
        groupCode: 'defaults',
        labelAr: 'طريقة الدفع الافتراضية',
        labelEn: 'Default Payment Method',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'CASH',
        options: [
            { value: 'CASH', labelAr: 'نقداً', labelEn: 'Cash' },
            { value: 'BANK', labelAr: 'بنك', labelEn: 'Bank' },
            { value: 'CREDIT', labelAr: 'ذمم', labelEn: 'Credit' },
        ],
        sortOrder: 60,
    },
    {
        key: 'html_templates.enable_custom_html',
        groupCode: 'html_templates',
        labelAr: 'تفعيل نماذج HTML المخصصة',
        labelEn: 'Enable Custom HTML Templates',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        sortOrder: 10,
    },
    {
        key: 'html_templates.invoice_template',
        groupCode: 'html_templates',
        labelAr: 'نموذج فاتورة HTML',
        labelEn: 'Invoice HTML Template',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: '<h1>{{company_name}}</h1><p>{{invoice_no}}</p>',
        sortOrder: 20,
    },
    {
        key: 'html_templates.receipt_template',
        groupCode: 'html_templates',
        labelAr: 'نموذج سند HTML',
        labelEn: 'Voucher HTML Template',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: '<h1>{{voucher_no}}</h1><p>{{amount}}</p>',
        sortOrder: 30,
    },
    {
        key: 'html_templates.variables',
        groupCode: 'html_templates',
        labelAr: 'متغيرات النماذج',
        labelEn: 'Template Variables',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { key: 'company_name', description: 'اسم الشركة' },
            { key: 'document_no', description: 'رقم المستند' },
        ],
        metadata: tableColumns([
            { key: 'key', labelAr: 'المتغير', labelEn: 'Variable' },
            { key: 'description', labelAr: 'الوصف', labelEn: 'Description' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'header_name_address.header_style',
        groupCode: 'header_name_address',
        labelAr: 'نمط الترويسة',
        labelEn: 'Header Style',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'NAME_ADDRESS',
        options: [
            { value: 'LOGO_ONLY', labelAr: 'الشعار فقط', labelEn: 'Logo Only' },
            { value: 'NAME_ADDRESS', labelAr: 'اسم وعنوان', labelEn: 'Name & Address' },
            { value: 'FULL', labelAr: 'كامل', labelEn: 'Full' },
        ],
        sortOrder: 10,
    },
    {
        key: 'header_name_address.name_ar',
        groupCode: 'header_name_address',
        labelAr: 'اسم الترويسة عربي',
        labelEn: 'Header Name Arabic',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        sortOrder: 20,
    },
    {
        key: 'header_name_address.address_ar',
        groupCode: 'header_name_address',
        labelAr: 'عنوان الترويسة عربي',
        labelEn: 'Header Address Arabic',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: '',
        sortOrder: 30,
    },
    {
        key: 'header_name_address.show_logo',
        groupCode: 'header_name_address',
        labelAr: 'إظهار الشعار في الترويسة',
        labelEn: 'Show Logo in Header',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 40,
    },
    {
        key: 'footer.text_ar',
        groupCode: 'footer',
        labelAr: 'نص التذييل عربي',
        labelEn: 'Footer Text Arabic',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: 'شكراً لتعاملكم معنا',
        sortOrder: 10,
    },
    {
        key: 'footer.show_tax_id',
        groupCode: 'footer',
        labelAr: 'إظهار الرقم الضريبي في التذييل',
        labelEn: 'Show Tax ID in Footer',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 20,
    },
    {
        key: 'footer.alignment',
        groupCode: 'footer',
        labelAr: 'محاذاة التذييل',
        labelEn: 'Footer Alignment',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'CENTER',
        options: [
            { value: 'RIGHT', labelAr: 'يمين', labelEn: 'Right' },
            { value: 'CENTER', labelAr: 'وسط', labelEn: 'Center' },
            { value: 'LEFT', labelAr: 'يسار', labelEn: 'Left' },
        ],
        sortOrder: 30,
    },
    {
        key: 'footer.html',
        groupCode: 'footer',
        labelAr: 'HTML التذييل',
        labelEn: 'Footer HTML',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: '',
        sortOrder: 40,
    },
    {
        key: 'customer_balance_print_format.format',
        groupCode: 'customer_balance_print_format',
        labelAr: 'تنسيق كشف رصيد الزبون',
        labelEn: 'Customer Balance Format',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'SUMMARY',
        options: [
            { value: 'SUMMARY', labelAr: 'ملخص', labelEn: 'Summary' },
            { value: 'DETAILED', labelAr: 'تفصيلي', labelEn: 'Detailed' },
            { value: 'AGING', labelAr: 'أعمار ذمم', labelEn: 'Aging' },
        ],
        sortOrder: 10,
    },
    {
        key: 'customer_balance_print_format.show_aging',
        groupCode: 'customer_balance_print_format',
        labelAr: 'إظهار أعمدة الأعمار',
        labelEn: 'Show Aging Columns',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 20,
    },
    {
        key: 'customer_balance_print_format.message',
        groupCode: 'customer_balance_print_format',
        labelAr: 'رسالة كشف الحساب',
        labelEn: 'Statement Message',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: '',
        sortOrder: 30,
    },
    {
        key: 'customer_balance_print_format.show_signature',
        groupCode: 'customer_balance_print_format',
        labelAr: 'إظهار خانة التوقيع',
        labelEn: 'Show Signature Area',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 40,
    },
    {
        key: 'employee_attendance_error_template.template',
        groupCode: 'employee_attendance_error_template',
        labelAr: 'نص نموذج خطأ الدوام',
        labelEn: 'Attendance Error Template',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: 'الموظف {{employee_name}} لديه خطأ دوام في تاريخ {{date}}',
        needsReview: true,
        sortOrder: 10,
    },
    {
        key: 'employee_attendance_error_template.severity',
        groupCode: 'employee_attendance_error_template',
        labelAr: 'درجة الخطأ الافتراضية',
        labelEn: 'Default Error Severity',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'WARNING',
        options: [
            { value: 'INFO', labelAr: 'معلومة', labelEn: 'Info' },
            { value: 'WARNING', labelAr: 'تحذير', labelEn: 'Warning' },
            { value: 'CRITICAL', labelAr: 'حرج', labelEn: 'Critical' },
        ],
        needsReview: true,
        sortOrder: 20,
    },
    {
        key: 'employee_attendance_error_template.send_to_hr',
        groupCode: 'employee_attendance_error_template',
        labelAr: 'إرسال الخطأ للموارد البشرية',
        labelEn: 'Send Error to HR',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        needsReview: true,
        sortOrder: 30,
    },
    {
        key: 'employee_attendance_error_template.placeholders',
        groupCode: 'employee_attendance_error_template',
        labelAr: 'متغيرات نموذج أخطاء الدوام',
        labelEn: 'Attendance Error Placeholders',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { key: 'employee_name', description: 'اسم الموظف' },
            { key: 'date', description: 'التاريخ' },
        ],
        metadata: tableColumns([
            { key: 'key', labelAr: 'المتغير', labelEn: 'Variable' },
            { key: 'description', labelAr: 'الوصف', labelEn: 'Description' },
        ]),
        needsReview: true,
        sortOrder: 40,
    },
    {
        key: 'bills_of_exchange.enabled',
        groupCode: 'bills_of_exchange',
        labelAr: 'تفعيل الكمبيالات',
        labelEn: 'Enable Bills of Exchange',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 10,
    },
    {
        key: 'bills_of_exchange.prefix',
        groupCode: 'bills_of_exchange',
        labelAr: 'بادئة رقم الكمبيالة',
        labelEn: 'Bill Prefix',
        valueType: 'string',
        inputType: 'text',
        defaultValue: 'BOE',
        sortOrder: 20,
    },
    {
        key: 'bills_of_exchange.default_maturity_days',
        groupCode: 'bills_of_exchange',
        labelAr: 'أيام الاستحقاق الافتراضية',
        labelEn: 'Default Maturity Days',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 30,
        validation: { min: 0, max: 3650 },
        sortOrder: 30,
    },
    {
        key: 'bills_of_exchange.status_workflow',
        groupCode: 'bills_of_exchange',
        labelAr: 'حالات الكمبيالة',
        labelEn: 'Bill Status Workflow',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { status: 'DRAFT', label: 'مسودة', next: 'ISSUED' },
            { status: 'ISSUED', label: 'مصدر', next: 'PAID' },
        ],
        metadata: tableColumns([
            { key: 'status', labelAr: 'الحالة', labelEn: 'Status' },
            { key: 'label', labelAr: 'الوصف', labelEn: 'Label' },
            { key: 'next', labelAr: 'الحالة التالية', labelEn: 'Next' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'sms_templates.enabled',
        groupCode: 'sms_templates',
        labelAr: 'تفعيل الرسائل القصيرة',
        labelEn: 'Enable SMS',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        sortOrder: 10,
    },
    {
        key: 'sms_templates.provider',
        groupCode: 'sms_templates',
        labelAr: 'مزود SMS',
        labelEn: 'SMS Provider',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'MANUAL',
        options: [
            { value: 'MANUAL', labelAr: 'يدوي / غير مربوط', labelEn: 'Manual' },
            { value: 'HTTP_API', labelAr: 'HTTP API', labelEn: 'HTTP API' },
            { value: 'BISAN', labelAr: 'خدمة بيسان', labelEn: 'Bisan' },
        ],
        sortOrder: 20,
    },
    {
        key: 'sms_templates.sender_name',
        groupCode: 'sms_templates',
        labelAr: 'اسم المرسل',
        labelEn: 'Sender Name',
        valueType: 'string',
        inputType: 'text',
        defaultValue: 'WAFI',
        sortOrder: 30,
    },
    {
        key: 'sms_templates.variables',
        groupCode: 'sms_templates',
        labelAr: 'متغيرات الرسائل القصيرة',
        labelEn: 'SMS Variables',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { key: 'customer_name', description: 'اسم الزبون' },
            { key: 'balance', description: 'الرصيد' },
        ],
        metadata: tableColumns([
            { key: 'key', labelAr: 'المتغير', labelEn: 'Variable' },
            { key: 'description', labelAr: 'الوصف', labelEn: 'Description' },
        ]),
        sortOrder: 40,
    },
    {
        key: 'sms_creditor.template',
        groupCode: 'sms_creditor',
        labelAr: 'نص رسالة الدائن',
        labelEn: 'Creditor SMS Text',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: 'تم تسجيل إشعار دائن بقيمة {{amount}}. رصيدكم {{balance}}.',
        needsReview: true,
        sortOrder: 10,
    },
    {
        key: 'sms_creditor.send_on_credit_note',
        groupCode: 'sms_creditor',
        labelAr: 'الإرسال عند إشعار دائن',
        labelEn: 'Send on Credit Note',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'sms_creditor.language',
        groupCode: 'sms_creditor',
        labelAr: 'لغة رسالة الدائن',
        labelEn: 'Creditor SMS Language',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ar',
        options: languages,
        sortOrder: 30,
    },
    {
        key: 'sms_creditor.require_approval',
        groupCode: 'sms_creditor',
        labelAr: 'اعتماد قبل الإرسال',
        labelEn: 'Require Approval Before Sending',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 40,
    },
    {
        key: 'sms_debtor.template',
        groupCode: 'sms_debtor',
        labelAr: 'نص رسالة المدين',
        labelEn: 'Debtor SMS Text',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: 'تم تسجيل إشعار مدين بقيمة {{amount}}. رصيدكم {{balance}}.',
        needsReview: true,
        sortOrder: 10,
    },
    {
        key: 'sms_debtor.send_on_debit_note',
        groupCode: 'sms_debtor',
        labelAr: 'الإرسال عند إشعار مدين',
        labelEn: 'Send on Debit Note',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'sms_debtor.language',
        groupCode: 'sms_debtor',
        labelAr: 'لغة رسالة المدين',
        labelEn: 'Debtor SMS Language',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'ar',
        options: languages,
        sortOrder: 30,
    },
    {
        key: 'sms_debtor.include_balance',
        groupCode: 'sms_debtor',
        labelAr: 'تضمين الرصيد في الرسالة',
        labelEn: 'Include Balance in SMS',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: true,
        sortOrder: 40,
    },
    {
        key: 'customer_balance.sms_template',
        groupCode: 'customer_balance',
        labelAr: 'نص رسالة رصيد الزبون',
        labelEn: 'Customer Balance SMS Text',
        valueType: 'string',
        inputType: 'textarea',
        defaultValue: 'رصيدكم الحالي {{balance}} حتى تاريخ {{date}}.',
        sortOrder: 10,
    },
    {
        key: 'customer_balance.warning_threshold',
        groupCode: 'customer_balance',
        labelAr: 'حد تنبيه الرصيد',
        labelEn: 'Balance Warning Threshold',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 0,
        validation: { min: 0 },
        sortOrder: 20,
    },
    {
        key: 'customer_balance.send_schedule',
        groupCode: 'customer_balance',
        labelAr: 'جدولة إرسال الرصيد',
        labelEn: 'Balance SMS Schedule',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'MANUAL',
        options: [
            { value: 'MANUAL', labelAr: 'يدوي', labelEn: 'Manual' },
            { value: 'DAILY', labelAr: 'يومي', labelEn: 'Daily' },
            { value: 'MONTHLY', labelAr: 'شهري', labelEn: 'Monthly' },
        ],
        sortOrder: 30,
    },
    {
        key: 'customer_balance.include_due_invoices',
        groupCode: 'customer_balance',
        labelAr: 'تضمين الفواتير المستحقة',
        labelEn: 'Include Due Invoices',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 40,
    },
    {
        key: 'crm.include_open_orders_in_exposure',
        groupCode: 'customer_balance',
        labelAr: 'احتساب أوامر البيع المفتوحة ضمن انكشاف الزبون',
        labelEn: 'Include Open Orders in Customer Exposure',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        metadata: { legacyKey: true },
        sortOrder: 50,
    },
    {
        key: 'crm.include_undeposited_cheques_in_exposure',
        groupCode: 'customer_balance',
        labelAr: 'احتساب الشيكات غير المودعة ضمن انكشاف الزبون',
        labelEn: 'Include Undeposited Cheques in Customer Exposure',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        metadata: { legacyKey: true },
        sortOrder: 60,
    },
    {
        key: 'crm.include_returned_cheques_in_exposure',
        groupCode: 'customer_balance',
        labelAr: 'احتساب الشيكات الراجعة ضمن انكشاف الزبون',
        labelEn: 'Include Returned Cheques in Customer Exposure',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        metadata: { legacyKey: true },
        sortOrder: 70,
    },
    {
        key: 'payables.include_open_orders',
        groupCode: 'customer_balance',
        labelAr: 'احتساب أوامر الشراء المفتوحة ضمن انكشاف المورد',
        labelEn: 'Include Open Purchase Orders in Vendor Exposure',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        metadata: { legacyKey: true },
        sortOrder: 80,
    },
    {
        key: 'payables.include_issued_uncleared_cheques',
        groupCode: 'customer_balance',
        labelAr: 'احتساب الشيكات الصادرة غير المحصلة ضمن انكشاف المورد',
        labelEn: 'Include Issued Uncleared Cheques in Vendor Exposure',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        metadata: { legacyKey: true },
        sortOrder: 90,
    },
    {
        key: 'bisan_services_api.base_url',
        groupCode: 'bisan_services_api',
        labelAr: 'رابط خدمة بيسان',
        labelEn: 'Bisan API Base URL',
        valueType: 'string',
        inputType: 'text',
        defaultValue: '',
        needsReview: true,
        sortOrder: 10,
    },
    {
        key: 'bisan_services_api.api_key',
        groupCode: 'bisan_services_api',
        labelAr: 'مفتاح API',
        labelEn: 'API Key',
        valueType: 'string',
        inputType: 'password',
        defaultValue: '',
        isSensitive: true,
        needsReview: true,
        sortOrder: 20,
    },
    {
        key: 'bisan_services_api.sync_enabled',
        groupCode: 'bisan_services_api',
        labelAr: 'تفعيل المزامنة',
        labelEn: 'Enable Sync',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        needsReview: true,
        sortOrder: 30,
    },
    {
        key: 'bisan_services_api.timeout_seconds',
        groupCode: 'bisan_services_api',
        labelAr: 'مهلة الاتصال بالثواني',
        labelEn: 'Timeout Seconds',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 30,
        validation: { min: 1, max: 300 },
        sortOrder: 40,
    },
    {
        key: 'bisan_services_api.endpoints',
        groupCode: 'bisan_services_api',
        labelAr: 'نقاط الربط',
        labelEn: 'API Endpoints',
        valueType: 'table',
        inputType: 'table',
        defaultValue: [
            { name: 'customers', path: '/customers', enabled: 'false' },
            { name: 'invoices', path: '/invoices', enabled: 'false' },
        ],
        metadata: tableColumns([
            { key: 'name', labelAr: 'الاسم', labelEn: 'Name' },
            { key: 'path', labelAr: 'المسار', labelEn: 'Path' },
            { key: 'enabled', labelAr: 'فعال', labelEn: 'Enabled' },
        ]),
        needsReview: true,
        sortOrder: 50,
    },
    {
        key: 'security.password_min_length',
        groupCode: 'security',
        labelAr: 'الحد الأدنى لطول كلمة المرور',
        labelEn: 'Minimum Password Length',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 8,
        validation: { min: 4, max: 64 },
        sortOrder: 10,
    },
    {
        key: 'security.enforce_2fa',
        groupCode: 'security',
        labelAr: 'إلزام التحقق الثنائي',
        labelEn: 'Enforce 2FA',
        valueType: 'boolean',
        inputType: 'toggle',
        defaultValue: false,
        sortOrder: 20,
    },
    {
        key: 'security.session_timeout_minutes',
        groupCode: 'security',
        labelAr: 'مهلة الجلسة بالدقائق',
        labelEn: 'Session Timeout Minutes',
        valueType: 'number',
        inputType: 'number',
        defaultValue: 60,
        validation: { min: 5, max: 1440 },
        sortOrder: 30,
    },
    {
        key: 'security.settings_permission_mode',
        groupCode: 'security',
        labelAr: 'صلاحية تعديل الإعدادات',
        labelEn: 'Settings Permission Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'SYSTEM_SETTINGS',
        options: [
            { value: 'SYSTEM_SETTINGS', labelAr: 'صلاحية إعدادات النظام', labelEn: 'System Settings Permission' },
            { value: 'ADMIN_ONLY', labelAr: 'مدير النظام فقط', labelEn: 'Admin Only' },
            { value: 'SECTION_BASED', labelAr: 'حسب القسم', labelEn: 'Section Based' },
        ],
        sortOrder: 40,
    },
    {
        key: 'security.audit_settings_changes',
        groupCode: 'security',
        labelAr: 'تسجيل تعديلات الإعدادات',
        labelEn: 'Audit Settings Changes',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: true,
        sortOrder: 50,
    },
    {
        key: 'timezone.default_timezone',
        groupCode: 'timezone',
        labelAr: 'المنطقة الزمنية الافتراضية',
        labelEn: 'Default Timezone',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'Asia/Hebron',
        options: [
            { value: 'Asia/Hebron', labelAr: 'فلسطين - الخليل', labelEn: 'Palestine - Hebron' },
            { value: 'Asia/Jerusalem', labelAr: 'القدس', labelEn: 'Jerusalem' },
            { value: 'UTC', labelAr: 'UTC', labelEn: 'UTC' },
        ],
        sortOrder: 10,
    },
    {
        key: 'timezone.fiscal_day_start',
        groupCode: 'timezone',
        labelAr: 'وقت بداية اليوم المالي',
        labelEn: 'Fiscal Day Start',
        valueType: 'string',
        inputType: 'time',
        defaultValue: '00:00',
        sortOrder: 20,
    },
    {
        key: 'timezone.daylight_saving_mode',
        groupCode: 'timezone',
        labelAr: 'التوقيت الصيفي',
        labelEn: 'Daylight Saving Mode',
        valueType: 'select',
        inputType: 'select',
        defaultValue: 'AUTO',
        options: [
            { value: 'AUTO', labelAr: 'تلقائي', labelEn: 'Automatic' },
            { value: 'ON', labelAr: 'مفعل دائماً', labelEn: 'Always On' },
            { value: 'OFF', labelAr: 'معطل', labelEn: 'Off' },
        ],
        sortOrder: 30,
    },
    {
        key: 'timezone.allow_user_override',
        groupCode: 'timezone',
        labelAr: 'السماح للمستخدم بتغيير المنطقة الزمنية',
        labelEn: 'Allow User Timezone Override',
        valueType: 'boolean',
        inputType: 'checkbox',
        defaultValue: false,
        sortOrder: 40,
    },
];

